### ISSUE TITLE
Azure client should implement closable interface

### ISSUE THREAD

**Issue by dadoonet** [Azure/azure-sdk-for-java#1387]
When running simple unit tests like:

```java
@Test
public void testConnectWithKeySecret() throws Exception {
    ApplicationTokenCredentials credentials =
        new ApplicationTokenCredentials(CLIENT_ID, TENANT, SECRET, AzureEnvironment.AZURE);
    Azure azure = Azure.authenticate(credentials).withSubscription(SUBSCRIPTION_ID);
    VirtualMachines virtualMachines = azure.virtualMachines();
}
```

I'm getting some thread leaks:

```
SEVERE: 2 threads leaked from SUITE scope at org.elasticsearch.cloud.azure.arm.AzureARMClientTests: 
   1) Thread[id=18, name=Okio Watchdog, state=TIMED_WAITING, group=TGRP-AzureARMClientTests]
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:460)
        at okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:350)
        at okio.AsyncTimeout$Watchdog.run(AsyncTimeout.java:313)
   2) Thread[id=17, name=OkHttp ConnectionPool, state=TIMED_WAITING, group=TGRP-AzureARMClientTests]
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:460)
        at okhttp3.ConnectionPool$1.run(ConnectionPool.java:66)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

Actually, the azure client should have a `close()` method which closes any opened resource like OkHttp or any Rest client.

Can you add that?

The workaround I think for now is to provide myself such clients and close them when my application or my test stops.

Thoughts?

**Comment by jianghaolu** [comment]
Hi @dadoonet 
Sorry about getting back to you late.

I wasn't able to reproduce this issue but I found an used thread pool in AzureClient earlier, which might solve your issue: https://github.com/Azure/autorest-clientruntime-for-java/pull/167. This will be available in maven central in the first week of June.

At the same time, can you share your environment so that I can try if I can reproduce this? 
1) Your OS
2) Your JDK version
3) IDE you are using, or from command line
4) Any special setup to run this test your provided
will all be really helpful information for me to track down the issue.

Thanks.

**Comment by dadoonet** [comment]
Hey! Thanks and no worries.

1. Mac OS
2. I don't remember what I was running when I opened the issue but it was for sure a 1.8 version. ATM I'm running `java version "1.8.0_121"`
3. IntelliJ.
4. Well. I'm using [Randomized Testing framework](https://labs.carrotsearch.com/randomizedtesting.html) to run all my tests. This framework checks for leaked threads before closing.

If you can't reproduce yourself, I can try to find some spare time to create a minimal project which reproduces that with a simple `mvn test` call.

**Comment by jianghaolu** [comment]
@dadoonet Yes that'll be great! 

At the same time, can you try using `1.0.3-SNAPSHOT` of `azure-client-runtime`? I fixed a leaked thread issue but not sure if it's what caused yours.

**Comment by dadoonet** [comment]
So what I would exactly change in my gradle build file here?

It's not super straightforward apparently.

I have this:

```groovy
versions << [
  'azure': '1.0.0-beta4.1',
  'adal4j': '1.1.2',
  'okhttp3': '3.3.1',
  'retrofit': '2.0.2'
]

repositories {
  maven {
    url "https://oss.sonatype.org/content/repositories/snapshots/"
  }
}

dependencies {
  compile "com.microsoft.azure:azure:${versions.azure}"
  compile "com.microsoft.azure:azure-mgmt-compute:${versions.azure}"
  compile "com.microsoft.azure:azure-mgmt-storage:${versions.azure}"
  compile "com.microsoft.azure:azure-mgmt-resources:${versions.azure}"
  compile "com.microsoft.azure:azure-mgmt-network:${versions.azure}"
  compile "com.microsoft.azure:azure-mgmt-keyvault:${versions.azure}"
  compile "com.microsoft.azure:azure-mgmt-graph-rbac:${versions.azure}"
  compile "com.microsoft.azure:azure-mgmt-batch:${versions.azure}"
  compile "com.microsoft.azure:azure-mgmt-trafficmanager:${versions.azure}"
  compile "com.microsoft.azure:azure-mgmt-appservice:${versions.azure}"
  compile "com.microsoft.azure:azure-mgmt-sql:${versions.azure}"
  compile "com.microsoft.azure:azure-mgmt-redis:${versions.azure}"
  compile "com.microsoft.azure:azure-mgmt-dns:${versions.azure}"
  compile "com.microsoft.azure:azure-mgmt-cdn:${versions.azure}"
  compile "com.microsoft.azure:azure-client-authentication:1.0.3-SNAPSHOT"
  compile "com.microsoft.azure:azure-client-runtime:1.0.3-SNAPSHOT"
  compile "com.microsoft.rest:client-runtime:1.0.3-SNAPSHOT"
  compile "com.squareup.okhttp3:okhttp:${versions.okhttp3}"
  compile "com.squareup.okhttp3:logging-interceptor:${versions.okhttp3}"
  compile "com.squareup.okhttp3:okhttp-urlconnection:${versions.okhttp3}"
  compile "com.microsoft.azure:adal4j:${versions.adal4j}"
  compile "com.squareup.retrofit2:retrofit:${versions.retrofit}"
  compile "com.squareup.retrofit2:adapter-rxjava:${versions.retrofit}"
  compile "io.reactivex:rxjava:1.1.8"
  compile "com.squareup.okio:okio:1.8.0"
  // TODO should we declare jackson version ${versions.jackson} instead? but warning we have a 2.8.x in global settings
  compile "com.fasterxml.jackson.core:jackson-databind:2.7.2"
  compile "com.fasterxml.jackson.datatype:jackson-datatype-joda:2.7.2"
  // TODO should we declare jackson version ${versions.jackson} instead? but warning we have a 2.8.x in global settings
  // Note that there is a bug to be reported at MS Azure project as they are not using a consistent version
  compile "com.fasterxml.jackson.core:jackson-annotations:2.7.0"
  compile "com.nimbusds:nimbus-jose-jwt:3.1.2"
  compile "com.nimbusds:oauth2-oidc-sdk:4.5"
  // TODO should we declare slf4j version ${versions.slf4j} instead? but warning we have a 1.6.2 in global settings
  compile "org.slf4j:slf4j-api:1.7.5"
  compile "net.minidev:json-smart:1.1.1"
  compile "org.apache.commons:commons-lang3:3.3.1"
  compile "commons-codec:commons-codec:${versions.commonscodec}"
  compile "javax.mail:mail:1.4.7"
  compile "com.google.code.gson:gson:2.2.4"
  compile "com.google.guava:guava:18.0"
  compile "org.apache.logging.log4j:log4j-slf4j-impl:${versions.log4j}"
  compile 'com.microsoft.azure:api-annotations:0.0.1'
}
```

But it fails to find some classes at runtime.
Any idea of what is missing?

**Comment by dadoonet** [comment]
So I created a sample project available at https://github.com/dadoonet/azuretest

Change your credentials in https://github.com/dadoonet/azuretest/blob/master/src/test/java/fr/pilato/test/azure/AzureTest.java#L41-L44

Then run:

```
mvn test
```

And boom...

```
[INFO] --- junit4-maven-plugin:2.5.0:junit4 (unit-tests) @ azure-arm-test ---
[INFO] <JUnit4> says olá! Master seed: CFEF8F1CCEF477ED
Executing 1 suite with 1 JVM.

Started J0 PID(59129@MacBook-Pro-David.local).
  2> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
  2> SLF4J: Defaulting to no-operation (NOP) logger implementation
  2> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
  2> mai 23, 2017 8:12:23 PM com.carrotsearch.randomizedtesting.ThreadLeakControl checkThreadLeaks
  2> GRAVE: 2 threads leaked from TEST scope at testConnectWithKeySecret(fr.pilato.test.azure.AzureTest): 
  2>    1) Thread[id=16, name=Okio Watchdog, state=TIMED_WAITING, group=TGRP-AzureTest]
  2>         at java.lang.Object.wait(Native Method)
  2>         at java.lang.Object.wait(Object.java:460)
  2>         at okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:350)
  2>         at okio.AsyncTimeout$Watchdog.run(AsyncTimeout.java:313)
  2>    2) Thread[id=15, name=OkHttp ConnectionPool, state=TIMED_WAITING, group=TGRP-AzureTest]
  2>         at java.lang.Object.wait(Native Method)
  2>         at java.lang.Object.wait(Object.java:460)
  2>         at okhttp3.ConnectionPool$1.run(ConnectionPool.java:66)
  2>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  2>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  2>         at java.lang.Thread.run(Thread.java:745)
  2> mai 23, 2017 8:12:23 PM com.carrotsearch.randomizedtesting.ThreadLeakControl tryToInterruptAll
  2> INFOS: Starting to interrupt leaked threads:
  2>    1) Thread[id=16, name=Okio Watchdog, state=TIMED_WAITING, group=TGRP-AzureTest]
  2>    2) Thread[id=15, name=OkHttp ConnectionPool, state=TIMED_WAITING, group=TGRP-AzureTest]
HEARTBEAT J0 PID(59129@MacBook-Pro-David.local): 2017-05-23T20:12:25, stalled for 11.0s at: AzureTest.testConnectWithKeySecret
  2> mai 23, 2017 8:12:27 PM com.carrotsearch.randomizedtesting.ThreadLeakControl tryToInterruptAll
  2> GRAVE: There are still zombie threads that couldn't be terminated:
  2>    1) Thread[id=16, name=Okio Watchdog, state=WAITING, group=TGRP-AzureTest]
  2>         at java.lang.Object.wait(Native Method)
  2>         at java.lang.Object.wait(Object.java:502)
  2>         at okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:338)
  2>         at okio.AsyncTimeout$Watchdog.run(AsyncTimeout.java:313)
  2>    2) Thread[id=15, name=OkHttp ConnectionPool, state=TIMED_WAITING, group=TGRP-AzureTest]
  2>         at java.lang.Object.wait(Native Method)
  2>         at java.lang.Object.wait(Object.java:460)
  2>         at okhttp3.ConnectionPool$1.run(ConnectionPool.java:66)
  2>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  2>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  2>         at java.lang.Thread.run(Thread.java:745)
ERROR   12.4s | AzureTest.testConnectWithKeySecret <<<
   > Throwable #1: com.carrotsearch.randomizedtesting.ThreadLeakError: 2 threads leaked from TEST scope at testConnectWithKeySecret(fr.pilato.test.azure.AzureTest): 
   >    1) Thread[id=16, name=Okio Watchdog, state=TIMED_WAITING, group=TGRP-AzureTest]
   >         at java.lang.Object.wait(Native Method)
   >         at java.lang.Object.wait(Object.java:460)
   >         at okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:350)
   >         at okio.AsyncTimeout$Watchdog.run(AsyncTimeout.java:313)
   >    2) Thread[id=15, name=OkHttp ConnectionPool, state=TIMED_WAITING, group=TGRP-AzureTest]
   >         at java.lang.Object.wait(Native Method)
   >         at java.lang.Object.wait(Object.java:460)
   >         at okhttp3.ConnectionPool$1.run(ConnectionPool.java:66)
   >         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
   >         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
   >         at java.lang.Thread.run(Thread.java:745)
   >    at __randomizedtesting.SeedInfo.seed([CFEF8F1CCEF477ED:91393764411FC68D]:0)
   > Throwable #2: com.carrotsearch.randomizedtesting.ThreadLeakError: There are still zombie threads that couldn't be terminated:
   >    1) Thread[id=16, name=Okio Watchdog, state=WAITING, group=TGRP-AzureTest]
   >         at java.lang.Object.wait(Native Method)
   >         at java.lang.Object.wait(Object.java:502)
   >         at okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:338)
   >         at okio.AsyncTimeout$Watchdog.run(AsyncTimeout.java:313)
   >    2) Thread[id=15, name=OkHttp ConnectionPool, state=TIMED_WAITING, group=TGRP-AzureTest]
   >         at java.lang.Object.wait(Native Method)
   >         at java.lang.Object.wait(Object.java:460)
   >         at okhttp3.ConnectionPool$1.run(ConnectionPool.java:66)
   >         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
   >         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
   >         at java.lang.Thread.run(Thread.java:745)
   >    at __randomizedtesting.SeedInfo.seed([CFEF8F1CCEF477ED:91393764411FC68D]:0)
  2> mai 23, 2017 8:12:27 PM com.carrotsearch.randomizedtesting.ThreadLeakControl checkThreadLeaks
  2> GRAVE: 2 threads leaked from SUITE scope at fr.pilato.test.azure.AzureTest: 
  2>    1) Thread[id=16, name=Okio Watchdog, state=WAITING, group=TGRP-AzureTest]
  2>         at java.lang.Object.wait(Native Method)
  2>         at java.lang.Object.wait(Object.java:502)
  2>         at okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:338)
  2>         at okio.AsyncTimeout$Watchdog.run(AsyncTimeout.java:313)
  2>    2) Thread[id=15, name=OkHttp ConnectionPool, state=TIMED_WAITING, group=TGRP-AzureTest]
  2>         at java.lang.Object.wait(Native Method)
  2>         at java.lang.Object.wait(Object.java:460)
  2>         at okhttp3.ConnectionPool$1.run(ConnectionPool.java:66)
  2>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  2>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  2>         at java.lang.Thread.run(Thread.java:745)
  2> mai 23, 2017 8:12:27 PM com.carrotsearch.randomizedtesting.ThreadLeakControl tryToInterruptAll
  2> INFOS: Starting to interrupt leaked threads:
  2>    1) Thread[id=16, name=Okio Watchdog, state=WAITING, group=TGRP-AzureTest]
  2>    2) Thread[id=15, name=OkHttp ConnectionPool, state=TIMED_WAITING, group=TGRP-AzureTest]
  2> mai 23, 2017 8:12:30 PM com.carrotsearch.randomizedtesting.ThreadLeakControl tryToInterruptAll
  2> GRAVE: There are still zombie threads that couldn't be terminated:
  2>    1) Thread[id=16, name=Okio Watchdog, state=WAITING, group=TGRP-AzureTest]
  2>         at java.lang.Object.wait(Native Method)
  2>         at java.lang.Object.wait(Object.java:502)
  2>         at okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:338)
  2>         at okio.AsyncTimeout$Watchdog.run(AsyncTimeout.java:313)
  2>    2) Thread[id=15, name=OkHttp ConnectionPool, state=TIMED_WAITING, group=TGRP-AzureTest]
  2>         at java.lang.Object.wait(Native Method)
  2>         at java.lang.Object.wait(Object.java:460)
  2>         at okhttp3.ConnectionPool$1.run(ConnectionPool.java:66)
  2>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
  2>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
  2>         at java.lang.Thread.run(Thread.java:745)
ERROR   0.00s | AzureTest (suite) <<<
   > Throwable #1: com.carrotsearch.randomizedtesting.ThreadLeakError: 2 threads leaked from SUITE scope at fr.pilato.test.azure.AzureTest: 
   >    1) Thread[id=16, name=Okio Watchdog, state=WAITING, group=TGRP-AzureTest]
   >         at java.lang.Object.wait(Native Method)
   >         at java.lang.Object.wait(Object.java:502)
   >         at okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:338)
   >         at okio.AsyncTimeout$Watchdog.run(AsyncTimeout.java:313)
   >    2) Thread[id=15, name=OkHttp ConnectionPool, state=TIMED_WAITING, group=TGRP-AzureTest]
   >         at java.lang.Object.wait(Native Method)
   >         at java.lang.Object.wait(Object.java:460)
   >         at okhttp3.ConnectionPool$1.run(ConnectionPool.java:66)
   >         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
   >         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
   >         at java.lang.Thread.run(Thread.java:745)
   >    at __randomizedtesting.SeedInfo.seed([CFEF8F1CCEF477ED]:0)
   > Throwable #2: com.carrotsearch.randomizedtesting.ThreadLeakError: There are still zombie threads that couldn't be terminated:
   >    1) Thread[id=16, name=Okio Watchdog, state=WAITING, group=TGRP-AzureTest]
   >         at java.lang.Object.wait(Native Method)
   >         at java.lang.Object.wait(Object.java:502)
   >         at okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:338)
   >         at okio.AsyncTimeout$Watchdog.run(AsyncTimeout.java:313)
   >    2) Thread[id=15, name=OkHttp ConnectionPool, state=TIMED_WAITING, group=TGRP-AzureTest]
   >         at java.lang.Object.wait(Native Method)
   >         at java.lang.Object.wait(Object.java:460)
   >         at okhttp3.ConnectionPool$1.run(ConnectionPool.java:66)
   >         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
   >         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
   >         at java.lang.Thread.run(Thread.java:745)
   >    at __randomizedtesting.SeedInfo.seed([CFEF8F1CCEF477ED]:0)

Tests with failures [seed: CFEF8F1CCEF477ED]:
  - fr.pilato.test.azure.AzureTest.testConnectWithKeySecret
  - fr.pilato.test.azure.AzureTest (suite)
```

**Comment by jianghaolu** [comment]
Thanks @dadoonet ! I verify that I can reproduce. Looking into it.

**Comment by jianghaolu** [comment]
Seems like a known issue from Okio: https://github.com/square/okio/issues/107. The fix they provided was adding a 60 seconds timeout - after being inactive for 60 seconds, the watchdog will shutdown.

So adding the following to your code:
```java
OkHttpClient okHttpClient = client.deployments().manager().inner().restClient().httpClient();
okHttpClient.dispatcher().executorService().shutdown();
okHttpClient.connectionPool().evictAll();
synchronized (okHttpClient.connectionPool()) {
    okHttpClient.connectionPool().notifyAll();
}
synchronized (AsyncTimeout.class) {
    AsyncTimeout.class.notifyAll();
}

Thread.sleep(60000);
```

and use 1.13.0 of Okio should mitigate the issue.

I've not yet able to find a solution that doesn't require this 60-second wait.

**Comment by jianghaolu** [comment]
You can view my code snippet at https://github.com/jianghaolu/azuretest/tree/okio13.

**Comment by dadoonet** [comment]
Thanks for the workaround! It works indeed.
That said it looks like a bad design IMO :) 

May be we should open an issue in Okio so they should provide a way to immediately shutdown with something like `shutdownNow()`?

Thoughts?

Not sure what to do now with the issue I opened here TBH. Should we close it or wait for a better workaround?

**Comment by jianghaolu** [comment]
This actually is suggested by other developers: https://github.com/square/okio/pull/114, https://github.com/square/okio/pull/243. Their argument is that for people who don't know about this they won't have thread leaks either - even though the thread is only cleaned up after a minute, and most tools would report a memory leak.

What I would do for this coming release is to bump up the version of Okio to 0.13.0. But I will hold on adding this workaround into `RestClient` until there's a clean immediate shutdown workaround.

**Comment by dadoonet** [comment]
Agreed. Thanks

**Comment by martinsawicki** [comment]
this was addressed by the introduction of the `.close()` method on the rest client in runtime v1.1.0

**Comment by dadoonet** [comment]
@martinsawicki Do you know how I can access the RestClient from the Azure client?

I mean that Azure class does not implement `Closeable` and does not expose a `close()` method AFAIK.
So I'm still seeing that behavior with Azure 1.13.0.
