### ISSUE TITLE
Resource Group name is not consistent within the resource ID of resources

### ISSUE THREAD

**Issue by kyle-wang-sd** [Azure/azure-sdk-for-java#1508]
For example, the resource group name of a virtual machine: 
https://management.azure.com/subscriptions/xxxxxxxxx-xxxxxxxxxxxxxx-xxxxxx/resourceGroups/**FOGLIGHTFORAD**/providers/Microsoft.Compute/virtualMachines/xxxxxx

While the resource group name of a network interface:
https://management.azure.com/subscriptions/xxxxxxxxx-xxxxxxxxxxxxxx-xxxxxx/resourceGroups/**FoglightForAD**/providers/Microsoft.Network/networkInterfaces/xxxxx 

This causes a problem that when using the resource id to query data in storage account, it cannot match.

Azure SDK version 1.0.0 beta 4.1

**Comment by anuchandy** [comment]
@kyle-wang-sd we are aware that casing of names in azure returned resource id is not consistent. 

Could you elaborate on what exactly is not working? Are you trying to fetch storage account resource  using `StorageAccounts.getByGroup(rgName, stgName)`? where rgName is the name you extracted from azure returned resource Id?

If you could share repro code then that will help us to debug.

**Comment by kyle-wang-sd** [comment]
Hi, @anuchandy 
Thanks for your quick response.

Here is our use case:
We have a VM on Azure, and enabled its diagnostics setting.
Now we would like to retrieve those diagnostic metrics from related Storage Account.
We use Azure Storage SDK to query the table of the Storage Account. the partition key is the match condition.

 We got the resource ID of VM through Azure SDK for Java: `VirtualMachine.id()`, and then translate the resource ID to a valid partition key. But as the case-sensitive issue (The group name within the resource ID is upper case), we are failed to match the partition key of Storage Account table, finally, got empty results by the query.

Now, we use the workaround to replace the upper case group name with real resource group name, but it is a little tricky.

Thanks,
Kyle.

**Comment by anuchandy** [comment]
thanks @kyle-wang-sd for details.

Hi @ravbhatnagar Gaurav, this is an issue due to the inconsistent casing of resource group name in resource id returned by various RPs. Here specifically the problem is casing of resource id used by CRP to create WADMetrics::partition-key is different from the one that is returned via GET.

I have seen casing of resource's resource id differs when it is retrieved by GET resource vs LIST.

**Comment by ImranBijapuri** [comment]
Any updates on this issue ?

**Comment by martinsawicki** [comment]
I believe in Azure ARM rules, resource names are case-insensitive, so REST APIs from various services may be free to return whatever casing they happen to return.
In the future, we'll probably need to lower-case them all in the SDK to enable easier lookups...

**Comment by anuchandy** [comment]
After some offline discussion with ARM and CRP, ARM team [@rjmax] agreed that this is something they need to fix in the ARM. RGBUG:10002143.

**Comment by martinsawicki** [comment]
closing on the SDK side, as this issue is being addressed in the Azure service side.

**Comment by vaibhavkulkar** [comment]
Is this issue fixed ? We are seeing this happening for virtualMachine id SDK 1.3.0

**Comment by ashishdhar** [comment]
Its still happening for a lot of azure resources. Can you please provide an ETA on when it will be fixed.
