### ISSUE TITLE
[BUG]Nonstandard logger names in RequestResponseChannel make logger configuration difficult

### ISSUE THREAD

**Issue by chadshowalter** [Azure/azure-sdk-for-java#15802]
**Description**
The logger created by RequestResponseChannel.java includes the word "class" prepended to the logger's name. 
This makes it impossible, for example, to configure this logger using standard spring boot configuration, e.g., 
`logging.level.com.azure=WARN`

***Code Snippet***
The line of code that creates the logger is 
`this.logger = new ClientLogger(String.format("%s<%s>", RequestResponseChannel.class, linkName));`

Note that the String.format call as shown above resolves, for example, to 
`class com.azure.core.amqp.implementation.RequestResponseChannel<mgmt-session>` and potentially other variants

Particularly, note that RequestResponseChannel.class.toString() prepends the word "class", resolving to 
`class com.azure.core.amqp.implementation.RequestResponseChannel`.  I suspect the author intended something more like this:
`this.logger = new ClientLogger(String.format("%s<%s>", RequestResponseChannel.class.getName(), linkName));`
which would create a logger named
`com.azure.core.amqp.implementation.RequestResponseChannel<link name>`

**Expected behavior**
I would expect that adding `logging.level.com.azure=WARN` to the application.properties file in a Spring Boot application would result in suppressing INFO level logs from the RequestResponseChannel logger.  It currently does not.

**Setup (please complete the following information):**
 - OS: macOS 10.15.6
 - IDE : IntelliJ
 - using com.azure:azure-messaging-eventhubs:5.2.0 and com.azure:azure-messaging-eventhubs-checkpointstore-blob:1.2.0

**Comment by srnagar** [comment]
@chadshowalter Thank you for reporting this issue. We will have the names of the loggers fixed in our upcoming release.

**Comment by srnagar** [comment]
This is fixed in com.azure:azure-messaging-eventhubs:5.3.0 and com.azure:azure-messaging-eventhubs-checkpointstore-blob:1.3.0

**Comment by arina-ielchiieva** [comment]
@srnagar looks like the same issue is still present in [ManagementChannel](https://github.com/Azure/azure-sdk-for-java/blob/3f31d68eed6fbe11516ca3afe3955c8840a6e974/sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/ManagementChannel.java#L37) and [ReactorConnection](https://github.com/Azure/azure-sdk-for-java/blob/3f31d68eed6fbe11516ca3afe3955c8840a6e974/sdk/core/azure-core-amqp/src/main/java/com/azure/core/amqp/implementation/ReactorConnection.java#L400).
