### ISSUE TITLE
[TA] [Service Bug] temporally having 'latest' as the default value of 'modelVersion'

### ISSUE THREAD

**Issue by mssfang** [Azure/azure-sdk-for-java#17625]
After service support null value for 'modelVersion', remove this temporally default value, 'latest'.

**Comment by samvaity** [comment]
Do we have a tentative date/roll-out period when this should be fixed/supported by the service team?

**Comment by mssfang** [comment]
still having this issue in the v3.1-preview.4. Looking for it get to be resolved before v3.1-preview.5 is released

**Comment by mssfang** [comment]
service team fixed it. Verified on v3.1-preview.5
