### ISSUE TITLE
[azure-servicebus-jms-spring-boot-starter] not able to set Content-type for Service Bus

### ISSUE THREAD

**Issue by bilak** [Azure/azure-sdk-for-java#18852]
[Enter feedback here]
Hello,
when I send an message from spring's `JmsTemplate` message is being automatically created as an XML inside servicebus. However this is creating other issues for us as we are trying to use only `application/json` type. Is there any option how to configure producer to store messages in service bus as a `application/json` instead of `application/xml`?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 18fcddaf-0239-c6b4-419f-545e599c96e8
* Version Independent ID: 0ca2e9c0-9067-56d0-c994-6e880134e6c7
* Content: [Azure Service Bus JMS Spring Boot Starter client library for Java](https://docs.microsoft.com/en-us/java/api/overview/azure/spring-boot-starter-servicebus-jms-readme?view=azure-java-stable)
* Content Source: [docs-ref-services/latest/spring-boot-starter-servicebus-jms-readme.md](https://github.com/Azure/azure-docs-sdk-java/blob/master/docs-ref-services/latest/spring-boot-starter-servicebus-jms-readme.md)
* Service: **springboot**
* Product: **azure**
* Technology: **azure**
* GitHub Login: @maggiepint
* Microsoft Alias: **magpint**

**Comment by yiliuTo** [comment]
@lu-cheng , please help to look into this issue, thanks.

**Comment by yiliuTo** [comment]
Hi @bilak , sorry for the late response. We have been investigating your issue and `spring-jms` library we used these days, and we found that it's such a pity that spring jms doesn't support custom message header, so we cannot modify messages' content type, which is already defined by jms specification.

**Comment by bilak** [comment]
Do you guys even know what libraries you use underneath your own libraries? 
Again it's a shame that you provide library and your team (even support!!!) doesn't know anything about it :-1: 

```
import java.io.IOException;

import javax.jms.BytesMessage;
import javax.jms.JMSException;
import javax.jms.Session;

import org.apache.qpid.jms.message.JmsBytesMessage;
import org.apache.qpid.jms.provider.amqp.message.AmqpJmsMessageFacade;
import org.apache.qpid.proton.amqp.Symbol;
import org.springframework.jms.support.converter.MappingJackson2MessageConverter;
import org.springframework.jms.support.converter.MessageType;

import com.fasterxml.jackson.databind.ObjectWriter;

public class CustomMappingJackson2MessageConverter extends MappingJackson2MessageConverter {

  public static final String TYPE_ID_PROPERTY = "_type";
  public static final String CONTENT_TYPE = "application/json";

  public CustomMappingJackson2MessageConverter() {
    this.setTargetType(MessageType.BYTES);
    this.setTypeIdPropertyName(TYPE_ID_PROPERTY);
  }

  @Override
  protected BytesMessage mapToBytesMessage(Object object, Session session, ObjectWriter objectWriter)
      throws JMSException, IOException {
    final BytesMessage message = super.mapToBytesMessage(object, session, objectWriter);
    JmsBytesMessage msg = (JmsBytesMessage) message;
    AmqpJmsMessageFacade facade = (AmqpJmsMessageFacade) msg.getFacade();
    facade.setContentType(Symbol.valueOf(CONTENT_TYPE));
    return msg;
  }
}
```

**Comment by yiliuTo** [comment]
Hi @bilak , I feel quite sorry that due to my personal unfamiliarity with qpid-jms-client, I have blocked you for such a long time. At the beginning I tried to solve it from amqp side, but after seeing the reply of your stackoverflow issue then I gave up and turned to spring jms. Again that's all because of my personal capabilities and I have learnt a lot now.
A good job of you.

**Comment by yiliuTo** [comment]
Hi @bilak , we now support configuring message converter bean to set content-type, here is the [pr](https://github.com/Azure/azure-sdk-for-java/pull/19346) and you can wait for our next release.

**Comment by yiliuTo** [comment]
Hi @bilak , we have published version 3.2.0 of azure-spring-boot-starter-servicebus-jms to Maven, you can refer to https://mvnrepository.com/artifact/com.azure.spring/azure-spring-boot-starter-servicebus-jms/3.2.0.

**Comment by bilak** [comment]
And what is the solution in that release? Because in PR above there is nothing that resolves issue, it's still not possible to send message as `application/json`. You've just removed default jms template but I can't see any documentation nor helper class that will create a jms template with proper configuration.

**Comment by yiliuTo** [comment]
@bilak , we remove the default jms template and use Spring framework's jms template which can pick up a message converter bean. So in the latest release, you could configure a custom message converter as you need and modify the content-type. Here is the [doc](https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-starter-servicebus-jms#set-content-type-of-messages).

**Comment by meenarc** [comment]
Is there a way by which the I can access the Retry count via the QPID JMS Spring SDK?
Basically be able to access any of the headers mentioned at https://docs.microsoft.com/en-us/rest/api/servicebus/message-headers-and-properties#message-headers

**Comment by yiliuTo** [comment]
Hi @meenarc , for the failover.maxReconnectAttempts and other headers you mentioned, we currently don't provide a way to configure them. For headers in https://docs.microsoft.com/en-us/rest/api/servicebus/message-headers-and-properties#message-headers, you can configure part of them by setting Spring JMS message properties, for example:
```
    @PostMapping("/topic")
    public String postMessage(@RequestParam String message) {
        jmsTemplate.convertAndSend(TOPIC_NAME, new User(message), m -> {
            m.setJMSCorrelationID("correlation-id");
            return m;
        });

        return message;
    }
```

Or you can also customize the message converter like the above comment and use `AmqpJmsMessageFacade` to set the AMQP message properties directly.

**Comment by meenarc** [comment]
Thanks. Am looking to do a retry with exponential backoff..Currently we can implement it using scheduled messages and adding some custom headers and some retry multiplier implementation in the scheduled message sender. Is there a cleaner, configurable way to do this?

**Comment by backwind1233** [comment]
> Thanks. Am looking to do a retry with exponential backoff..Currently we can implement it using scheduled messages and adding some custom headers and some retry multiplier implementation in the scheduled message sender. Is there a cleaner, configurable way to do this?

@meenarc currently, we do not support a configurable way to do this, but I am developing this feature now, it will be released soon.
