### ISSUE TITLE
Event Hubs 5.7.1 regression

### ISSUE THREAD

**Issue by jayr-davis** [Azure/azure-sdk-for-java#22007]
byte[] payloadBytes = jsonString.getBytes() ;
log.debug("Sending step 1");
// now that we have the client, send the data
EventData sendEvent = new EventData(payloadBytes) ;
log.debug("Sending step 2");

When using <azure-messaging-eventhubs.version>5.7.1</azure-messaging-eventhubs.version>, I never see "Sending step 2".

When using <azure-messaging-eventhubs.version>5.4.0</azure-messaging-eventhubs.version>, it works/ it returns.

Change made to pom.xml only and code went BACK to working after pom+code changes caused hang.

Versions
OpenJDK 64-Bit Server VM Corretto-8.272.10.3 (build 25.272-b10, mixed mode)
Linux WL-Test-FBP-1c79 5.4.0-1037-aws #39~18.04.1-Ubuntu SMP Fri Jan 15 02:48:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux (i.e., an AWS box)

REAL cut-n-dry difference. I note that the constructor has significantly changed.

**Comment by joshfree** [comment]
@conniey could you please take a look?

**Comment by conniey** [comment]
* Can you show me your `mvn dependency:tree -Dverbose -Dincludes=com.azure:*`.
    * What version of azure-core is being resolved?
* Are you using azure-messaging-eventhubs-checkpointstore-blobs, 1.7.0?

**Comment by jayr-davis** [comment]
[output_from_mvn.txt](https://github.com/Azure/azure-sdk-for-java/files/6586726/output_from_mvn.txt)

Note:  Could not get the -Dincludes to work, so I dropped that.

**Comment by conniey** [comment]
@jayr-davis Hey. 

* I tried the minimal repro and I was able to get the output expected. 
* From your dependency tree, it looks there there is a dependency conflict which we resolved by releasing [azure-messaging-eventhubs-checkpointstore-blob 1.7.1](https://search.maven.org/artifact/com.azure/azure-messaging-eventhubs-checkpointstore-blob/1.7.1/jar).

If this does not resolve your issue, can you set the environment variable AZURE_LOG_LEVEL=1 and then run your code, it should show some debug output that could help me understand some more.

**Comment by jayr-davis** [comment]
Nope.
I upgraded to blob 1.7.1 and eventHubs 5.7.1 and my code still hangs.

I am trying to run with your debug flag ...

**Comment by jayr-davis** [comment]
Set the environment var; checked my log4j xml file.  Got no output.
Changed my pom back to 5.40 and 1.1.0 and everything works.
So something is hanging or generating an exception that is not being shown or something.

**Comment by conniey** [comment]
That's so weird. Do you have a minimal repro for me to try?

**Comment by jayr-davis** [comment]
Not really.
Here are the "operative" code snippets:

EventHubProducerClient	ehClient = new EventHubClientBuilder().connectionString(locConnStr).buildProducerClient();

byte[] payloadBytes = jsonString.getBytes() ;
EventData sendEvent = new EventData(payloadBytes) ;
EventDataBatch batch = ehClient.createBatch();
ehClient.send(batch);


ehClient.close();


That's BASICALLY all I'm doing.  Yes I'm doing those from multiple threads at vaguely the same time to multiple different EventHub clients.  But that all works fine with the older libraries.  I change the libraries and it hangs somewhere and I stop processing data.

This MAY be a "weird path"...but I started a year or so ago, and this was the path through the code that I got to work.

NOTE:  I started so long ago (how long ago did he start?) 
I started so long ago that the EHClient would end up timing out after less than a second and close/hose itself.
Repeatedly.  So I ended up attaching a timestamp to the EHClient and closing it and re-opening it if it was TOO old.
Originally, too old meant 1 second.  I think I am using 10 seconds now.  I have no idea if I can set that to 5 mins or infinite.  But everything is working so I have no real reason to change it.

Thanks.

**Comment by conniey** [comment]
@jayr-davis Hey, apologies for not getting back to this. We did many reliability fixes in the last few months, so 5.10.0 is a lot more stable and you shouldn't see those timeout exceptions and if you do, it should recover.

For the behaviour where it crashes without any indication, could you set this environment variable: `AZURE_LOG_LEVEL=1` and run the same program? It should spit out some messages as to why it failed. You can also use additional loggers here: https://docs.microsoft.com/en-us/azure/developer/java/sdk/logging-overview
