### ISSUE TITLE
ConfigurationClient.listConfigurationSettings's iterator taking too long to iterate over settings. 

### ISSUE THREAD

**Issue by shashankkr** [Azure/azure-sdk-for-java#23277]
**Query/Question**
I am trying to iterate over listConfiguration setting and adding the key values to a hash map like this 
` HashMap<String, String> settingsMap = new HashMap<>();         
  ConfigurationClient client = new ConfigurationClientBuilder().connectionString(appConfigConnectionString).buildClient();
          logger.info("created config client");
          SettingSelector selector = new SettingSelector().setKeyFilter(keyPrefix).setLabelFilter(label);
          client.listConfigurationSettings(selector).forEach(setting -> {
            logger.info("reading config");
            settingsMap.put(setting.getKey(), setting.getValue());
        });`
But the iterator is taking 20-25 secs to iterate over the settings. 

***Why is this not a Bug or a feature Request?***
I dont know if this behavior is just in my local machine

**Setup (please complete the following information if applicable):**
 - OS: windows 10
 - IDE: vs code 
 - Library/Libraries: azure-core<1.18.0>, azure-data-appconfiguration <1.2.0>
 - JDK: MS OpenJDK
 
 **Information Checklist**
 Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [
![Screenshot 2021-07-31 020004](https://user-images.githubusercontent.com/244933/127730454-52a86f78-bc44-4b7b-bf75-5ae0e9548c6c.jpg)
 ] Query Added
- [ ] Setup information Added

**Comment by joshfree** [comment]
@mssfang can you please take a look?

**Comment by mssfang** [comment]
@shashankkr Thank you for reaching out to us!
How many settings are in your configuration store? I tried with "prefix-b" as the key prefix and added 2000 keys. It takes 5437milliseconds to listing the "prefix-b" prefix keys. Can you give more information?

**Comment by shashankkr** [comment]
@mssfang We don't have many settings, this is the first time we have started using app configurations, so I'll say 10 settings tops. 
I added appropriate logging to show you. This is my method which retrieves the settings from app config: 
`
 public HashMap<String,String> getSettingsMap(String label, String keyPrefix) throws Exception{
        HashMap<String, String> settingsMap = new HashMap<>();
          // create the app configuration client
          logger.info("2. Creating configuration client");
          ConfigurationClient client = new ConfigurationClientBuilder().connectionString(appConfigConnectionString)
          .buildClient();
          logger.info("3. created config client");
          SettingSelector selector = new SettingSelector().setKeyFilter(keyPrefix).setLabelFilter(label);
          logger.info("4. fetch app settings");
          client.listConfigurationSettings(selector).forEach(setting -> {
           if(setting.getKey().startsWith(keyPrefix.split(":")[0])){
            logger.info("5. got setting, adding it to hashmap");
            settingsMap.put(setting.getKey(), setting.getValue());
           } else{
                throw new RuntimeException(String.format("AppConfigSettings for key prefix %s not found",keyPrefix));
           }
        });
        logger.info("6. return hashmap");
        return settingsMap;


    }
`

And this is the output : 
![image](https://user-images.githubusercontent.com/244933/129132345-ae568329-ceac-4db4-81e5-4ceeff7d27ab.png)

I have highlighted the time it takes to iterate over the keys. So gettings the app settings is in milliseconds but iterator takes 20-30 secs.

**Comment by mrm9084** [comment]
Seems similar to https://github.com/Azure/azure-sdk-for-java/issues/22618

**Comment by mrm9084** [comment]
The issue is the VPN, in my case if I turn off my VPN it goes from like 2 seconds to 22 seconds in the test I just ran.
@joshfree

**Comment by mrm9084** [comment]
This should be solved in 1.2.1, works fine for me in that version.

**Comment by mssfang** [comment]
@shashankkr The version 1.2.1 just released on 8/11. Can you try it again? @mrm9084 and myself tried and only took 2 seconds to on the listing. Thanks @mrm9084.

If that doesn't works in your end, please let us know. We would like to know more about it.

**Comment by shashankkr** [comment]
Hi @mssfang ,
Upgraded to 1.2.1 but still seeing the same issue 
![image](https://user-images.githubusercontent.com/244933/129431818-04dd6325-ab96-4c32-b11d-6f38f66cda06.png)

Let me know what additional logs you want me to provide. Thanks.

**Comment by mrm9084** [comment]
@shashankkr You seem to be missing the SDK logs, @mssfang I found this for logging? https://github.com/Azure/azure-sdk-for-java/wiki/Logging-with-Azure-SDK.

This is what I see for logging.
```console
2021-08-16 09:19:58.687  INFO 26088 --- [nio-8080-exec-1] c.a.d.a.ConfigurationAsyncClient         : Listing ConfigurationSettings - SettingSelector(keyFilter=/application/*, labelFilter=null, acceptDateTime=null, fields=ALL_FIELDS)
2021-08-16 09:20:00.177  INFO 26088 --- [ctor-http-nio-1] c.a.d.a.ConfigurationAsyncClient         : Listed ConfigurationSettings - SettingSelector(keyFilter=/application/*, labelFilter=null, acceptDateTime=null, fields=ALL_FIELDS)
```

**Comment by mssfang** [comment]
@shashankkr  Seems you don't have SDK logs printed.

Can you try below code and print out the logs? (Set an environment variable `AZURE_LOG_LEVEL=2`)

```
    static HashMap<String,String> getSettingsMap(String label, String keyPrefix, String appConfigConnectionString){
        HashMap<String, String> settingsMap = new HashMap<>();
        // create the app configuration client
        logger.info("2. Creating configuration client");
        ConfigurationClient client = new ConfigurationClientBuilder().connectionString(appConfigConnectionString)
                                             .httpLogOptions(new HttpLogOptions().setLogLevel(HttpLogDetailLevel.BODY_AND_HEADERS))
                                             .buildClient();
        logger.info("3. created config client");
        SettingSelector selector = new SettingSelector().setKeyFilter(keyPrefix).setLabelFilter(label);
        logger.info("4. fetch app settings");
        final PagedIterable<ConfigurationSetting> configurationSettings = client.listConfigurationSettings(selector);
        configurationSettings.forEach(setting -> {
                logger.info("5. got setting, adding it to hashmap");
                settingsMap.put(setting.getKey(), setting.getValue());
        });
        logger.info("6. return hashmap");
        return settingsMap;
    }

```

My output: 

```
2021-08-16 16:57:07.398 [main] [INFO] HelloWorld - 2. Creating configuration client
2021-08-16 16:57:08.346 [main] [INFO] HelloWorld - 3. created config client
**2021-08-16 16:57:08.346 [main] [INFO] HelloWorld - 4. fetch app settings
2021-08-16 16:57:08.603 [main] [INFO] com.azure.data.appconfiguration.ConfigurationAsyncClient - Listing ConfigurationSettings - SettingSelector(keyFilter=prefix-b0, labelFilter=null, acceptDateTime=null, fields=ALL_FIELDS)
2021-08-16 16:57:08.962 [main] [INFO] com.azure.data.appconfiguration.ConfigurationService.listKeyValues - --> GET https://******.azconfig.io/kv?key=REDACTED&api-version=REDACTEDTry count: 1(empty body)--> END GET
2021-08-16 16:57:10.453 [reactor-http-nio-1] [INFO] com.azure.data.appconfiguration.ConfigurationService.listKeyValues - <-- 200 https://******.azconfig.io/kv?key=REDACTED&api-version=REDACTED (1497 ms, unknown-length body)(body content not logged)<-- END HTTP
2021-08-16 16:57:10.617 [reactor-http-nio-1] [INFO] com.azure.data.appconfiguration.ConfigurationAsyncClient - Listed ConfigurationSettings - SettingSelector(keyFilter=prefix-b0, labelFilter=null, acceptDateTime=null, fields=ALL_FIELDS)
2021-08-16 16:57:10.617 [main] [INFO] HelloWorld - 5. got setting, adding it to hashmap**
2021-08-16 16:57:10.617 [main] [INFO] HelloWorld - 5. got setting, adding it to hashmap
2021-08-16 16:57:10.617 [main] [INFO] HelloWorld - 6. return hashmap


```

**Comment by mssfang** [comment]
@mrm9084 Yes. It relocate to https://docs.microsoft.com/en-us/azure/developer/java/sdk/logging-overview for more information.

**Comment by mssfang** [comment]
@shashankkr Does it helps to resolve your issue?
