### ISSUE TITLE
[BUG] CosmosPageImpl Doesn't Correctly Calculate hasNext()

### ISSUE THREAD

**Issue by trande4884** [Azure/azure-sdk-for-java#32067]
**Describe the bug**
The constructor for CosmosPageImpl only sets `this.offset = pagealbe.getOffset();` however this does not work for any page other than the first page. If you are creating a page request object like `CosmosPageRequest pageRequest = new CosmosPageRequest(1, 2, null);` then no offset is being passed in, so the offset will get set to 0. Because of this function's like `hasNext()` and `isLast()` do not work correctly. The implementation likely needs to be something like `this.offset = pageable.getOffset() + (pageable.getPageNumber() * pageable.getPageSize());` so that it can account for the already processed results. However, the offset may not exactly be the correct place to do this so an alternative would be to add a new variable to CosmosPageImpl that is something like processedRecords which can be set to `pageable.getPageNumber() * pageable.getPageSize()` which can then be added to the offset in the hasNext() calculation.

**To Reproduce**
Generate a query that returns 4 results and grab a CosmosPageRequest such as `CosmosPageRequest pageRequest = new CosmosPageRequest(1, 2, null);` which will get the second page of results. With the result try retrieving `hasNext()` which should be false but it will return true.

**Expected behavior**
With the steps to reproduce above, hasNext() should return true.

If you suspect a dependency version mismatch (e.g. you see `NoClassDefFoundError`, `NoSuchMethodError` or similar), please check out [Troubleshoot dependency version conflict article](https://aka.ms/azsdk/java/dependency/troubleshoot) first. If it doesn't provide solution for the problem, please provide:
- verbose dependency tree (`mvn dependency:tree -Dverbose`)
- exception message, full stack trace, and any available logs

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by kushagraThapar** [comment]
@trande4884 is this still a valid issue? I believe we have fixed it. Please update it, thanks!

**Comment by trande4884** [comment]
This is still an issue. You can see below that even though this page is correctly getting "Page 2 of 2", calling page1.hasNext() is returning true when it should be returning false.
![image](https://github.com/Azure/azure-sdk-for-java/assets/63077034/71444775-bc1f-4431-b472-2e2a44d9d0b7)

**Comment by FabianMeiswinkel** [comment]
I don't quite get it - if the container has many physical partitions getting the second record doesn't mean hasNext should be false - because you would need to drain the query to cover for all the other partitions, correct? And while we suppress empty pages (except for the last one) in this case an empty last page is not really avoidable - unless you always retrieve one page in advance (which will become a problem when customers actually use a continuation token). The semantic of hasNext is only that it must guarantee that the query is fully drained when hasNext returns false. hasNext == true doesn't mean that there will be more records for sure - just that the query hasn't been fully drained yet.

**Comment by trande4884** [comment]
@FabianMeiswinkel to further clarify the issue isn't just that we could get 1 empty page if attempting to utilize hasNext(), you could get numerous empty pages like below. If you have a high offset and a low page size hasNext() will have you get many empty pages before actually returning false. Also in Spring, we get a count of all of the items across all partitions upfront, so we have the total count to cover all partitions from the time we get the first page and we should be able to accurately know when we have retrieved all the results.

![image](https://github.com/Azure/azure-sdk-for-java/assets/63077034/3d5aba43-2187-4d5d-a285-e3b0a71c8851)
