### ISSUE TITLE
[BUG] ServiceBusSenderClient cannot send messages to Azure Service Bus when using Azure Application gateway

### ISSUE THREAD

**Issue by YuliyaMaskvina** [Azure/azure-sdk-for-java#37990]
**Describe the bug**
Hello,

After 20 seconds of inactivity, the same instance of ServiceBusSenderClient cannot send messages anymore. The library cannot understand that the connection is aborted to recreate it (or recreate a new sender link). We are sending messages using Azure Application Gateway, 

Could you please assist ?

Thank you!

***Exception or Stack Trace***
2023-12-08T10:10:31.957+01:00  INFO 21496 --- [           main] c.j.s.ServicebusTestApplicationTests     : Started ServicebusTestApplicationTests in 2.665 seconds (process running for 4.107)
2023-12-08T10:10:32.429+01:00  INFO 21496 --- [           main] c.a.m.s.i.ServiceBusConnectionProcessor  : {"az.sdk.message":"Setting next AMQP channel.","entityPath":"N/A"}
2023-12-08T10:10:32.431+01:00  INFO 21496 --- [           main] c.a.m.s.ServiceBusClientBuilder          : # of open clients with shared connection: 1
2023-12-08T10:10:32.447+01:00  INFO 21496 --- [           main] c.j.s.ServicebusTestApplication          : Sending message test
2023-12-08T10:10:32.497+01:00  INFO 21496 --- [           main] c.a.c.a.i.ReactorConnection              : {"az.sdk.message":"Creating and starting connection.","connectionId":"MF_cbd4c6_1702026632336","hostName":"XXXXXXXXXXXXX
XXXXXXXXXXXXX","port":443}
2023-12-08T10:10:32.538+01:00  INFO 21496 --- [           main] c.a.c.a.implementation.ReactorExecutor   : {"az.sdk.message":"Starting reactor.","connectionId":"MF_cbd4c6_1702026632336"}
2023-12-08T10:10:32.546+01:00  INFO 21496 --- [ctor-executor-1] c.a.c.a.i.h.WebSocketsConnectionHandler  : {"az.sdk.message":"onConnectionInit","connectionId":"MF_cbd4c6_1702026632336","hostName":"XXXXXXXXXXXX","na
mespace":"XXXXXXXXXXXX.servicebus.windows.net"}
2023-12-08T10:10:32.546+01:00  INFO 21496 --- [ctor-executor-1] c.a.c.a.i.handler.ReactorHandler         : {"az.sdk.message":"reactor.onReactorInit","connectionId":"MF_cbd4c6_1702026632336"}
2023-12-08T10:10:32.547+01:00  INFO 21496 --- [ctor-executor-1] c.a.c.a.i.h.WebSocketsConnectionHandler  : {"az.sdk.message":"onConnectionLocalOpen","connectionId":"MF_cbd4c6_1702026632336","hostName":"XXXXXXXXXXX.servicebus.windows.net"}
2023-12-08T10:10:32.651+01:00  INFO 21496 --- [ctor-executor-1] c.a.c.a.i.h.WebSocketsConnectionHandler  : {"az.sdk.message":"onConnectionBound","connectionId":"MF_cbd4c6_1702026632336","hostName":"XXXXXXXXXXXXX","p
eerDetails":"XXXXXXXXXXXX:443"}
2023-12-08T10:10:32.651+01:00  INFO 21496 --- [ctor-executor-1] c.a.c.a.i.h.WebSocketsConnectionHandler  : {"az.sdk.message":"Adding web socket layer","connectionId":"MF_cbd4c6_1702026632336"}
2023-12-08T10:10:32.986+01:00  INFO 21496 --- [ctor-executor-1] c.a.c.a.i.h.WebSocketsConnectionHandler  : {"az.sdk.message":"onConnectionRemoteOpen","connectionId":"MF_cbd4c6_1702026632336","hostName":"XXXXXXXXXXXXX
XXXXXXXXXXXXX","remoteContainer":"90c15b65f0004068b6ba3d632ec06c9b_G12"}
2023-12-08T10:10:32.987+01:00  INFO 21496 --- [ctor-executor-1] c.a.m.s.i.ServiceBusConnectionProcessor  : {"az.sdk.message":"Channel is now active.","entityPath":"N/A"}
2023-12-08T10:10:33.011+01:00  INFO 21496 --- [ctor-executor-1] c.a.c.a.i.handler.SessionHandler         : {"az.sdk.message":"onSessionRemoteOpen","connectionId":"MF_cbd4c6_1702026632336","sessionName":"XXXXXXXXXXXXXy.v
1","sessionIncCapacity":0,"sessionOutgoingWindow":2147483647}
2023-12-08T10:10:33.021+01:00  INFO 21496 --- [ctor-executor-1] c.a.c.a.i.ReactorConnection              : {"az.sdk.message":"Setting CBS channel.","connectionId":"MF_cbd4c6_1702026632336"}
2023-12-08T10:10:33.033+01:00  INFO 21496 --- [ctor-executor-1] c.a.c.a.i.handler.SessionHandler         : {"az.sdk.message":"onSessionRemoteOpen","connectionId":"MF_cbd4c6_1702026632336","sessionName":"cbs-session","sessionIncC
apacity":0,"sessionOutgoingWindow":2147483647}
2023-12-08T10:10:33.045+01:00  INFO 21496 --- [ctor-executor-1] c.a.c.a.i.ReactorConnection              : {"az.sdk.message":"Emitting new response channel.","connectionId":"MF_cbd4c6_1702026632336","entityPath":"$cbs","linkName
":"cbs"}
2023-12-08T10:10:33.045+01:00  INFO 21496 --- [ctor-executor-1] c.a.c.a.i.AmqpChannelProcessor           : {"az.sdk.message":"Setting next AMQP channel.","connectionId":"MF_cbd4c6_1702026632336","entityPath":"$cbs"}
2023-12-08T10:10:33.269+01:00  INFO 21496 --- [ctor-executor-1] c.a.c.a.i.AmqpChannelProcessor           : {"az.sdk.message":"Next AMQP channel received.","connectionId":"MF_cbd4c6_1702026632336","entityPath":"$cbs","subscriberI
d":"un_fb7560_1702026633025"}
2023-12-08T10:10:33.284+01:00  INFO 21496 --- [ctor-executor-1] c.a.c.a.i.handler.SendLinkHandler        : {"az.sdk.message":"onLinkRemoteOpen","connectionId":"MF_cbd4c6_1702026632336","linkName":"cbs:sender","entityPath":"$cbs"
,"remoteTarget":"Target{address='$cbs', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, capabilities=null}"}
2023-12-08T10:10:33.285+01:00  INFO 21496 --- [ctor-executor-1] c.a.c.a.i.AmqpChannelProcessor           : {"az.sdk.message":"Channel is now active.","connectionId":"MF_cbd4c6_1702026632336","entityPath":"$cbs"}
2023-12-08T10:10:33.285+01:00  INFO 21496 --- [ctor-executor-1] c.a.c.a.i.handler.ReceiveLinkHandler     : {"az.sdk.message":"onLinkRemoteOpen","connectionId":"MF_cbd4c6_1702026632336","entityPath":"$cbs","linkName":"cbs:receive
r","remoteSource":"Source{address='$cbs', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, distributionMode=null, filter=null, defaultOutcome=null, outcomes=null, capabilities=null}"}
2023-12-08T10:10:34.243+01:00  INFO 21496 --- [onPool-worker-1] c.azure.identity.ClientSecretCredential  : Azure Identity => getToken() result for scopes [https://servicebus.azure.net/.default]: SUCCESS
2023-12-08T10:10:34.380+01:00  INFO 21496 --- [ctor-executor-1] c.a.c.a.i.ActiveClientTokenManager       : {"az.sdk.message":"Scheduling refresh token task.","scopes":"https://servicebus.azure.net/.default"}
2023-12-08T10:10:34.390+01:00  INFO 21496 --- [ctor-executor-1] c.a.c.a.implementation.ReactorSession    : {"az.sdk.message":"Creating a new send link.","connectionId":"MF_cbd4c6_1702026632336","linkName":"XXXXXXXXXXXXX
y.v1XXXXXXXXXXXXXy.v1","sessionName":"XXXXXXXXXXXXXy.v1"}
2023-12-08T10:10:34.435+01:00  INFO 21496 --- [ctor-executor-1] c.a.m.s.ServiceBusSenderAsyncClient      : {"az.sdk.message":"Sending batch.","batchSize":1}
2023-12-08T10:10:34.442+01:00  INFO 21496 --- [ctor-executor-1] c.a.c.a.i.handler.SendLinkHandler        : {"az.sdk.message":"onLinkRemoteOpen","connectionId":"MF_cbd4c6_1702026632336","linkName":"XXXXXXXXXXXXXXXXXXXXXXXXXX","entityPath":"XXXXXXXXXXXXX","remoteTarget":"Target{address='XXXXXXXXXXXXX', durable=NONE, expiryPolicy=SESSION_END, timeout=0, dynamic=false, dynamicNodeProperties=null, capabili
ties=null}"}
2023-12-08T10:10:34.488+01:00  INFO 21496 --- [           main] c.j.s.ServicebusTestApplication          : test message SENT
2023-12-08T10:10:44.491+01:00  INFO 21496 --- [           main] c.j.s.ServicebusTestApplication          : Sending message test2
2023-12-08T10:10:44.493+01:00  INFO 21496 --- [           main] c.a.m.s.ServiceBusSenderAsyncClient      : {"az.sdk.message":"Sending batch.","batchSize":1}
2023-12-08T10:10:44.520+01:00  INFO 21496 --- [           main] c.j.s.ServicebusTestApplication          : test2 message SENT
2023-12-08T10:11:04.530+01:00  INFO 21496 --- [           main] c.j.s.ServicebusTestApplication          : Sending test3
2023-12-08T10:11:04.531+01:00  INFO 21496 --- [           main] c.a.m.s.ServiceBusSenderAsyncClient      : {"az.sdk.message":"Sending batch.","batchSize":1}
2023-12-08T10:13:09.354+01:00 ERROR 21496 --- [     parallel-5] reactor.core.publisher.Operators         : Operator called default onErrorDropped

com.azure.core.amqp.exception.AmqpException: Entity(XXXXXXXXXXXXX): Send operation timed out, errorContext[NAMESPACE: XXXXXXXXXXXXX. ERROR CONTEXT: N/A, PATH: XXXXXXXXXXXXX, REFERENCE_ID: XXXXXXXXXXXXXXXXXXXXXXXXXXXX, LINK_CREDIT: 996]
        at com.azure.core.amqp.implementation.ReactorSender$SendTimeout.run(ReactorSender.java:869) ~[azure-core-amqp-2.8.13.jar:2.8.13]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) ~[reactor-core-3.6.0.jar:3.6.0]
        at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) ~[reactor-core-3.6.0.jar:3.6.0]
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:842) ~[na:na]

2023-12-08T10:15:10.133+01:00  INFO 21496 --- [           main] .s.b.a.l.ConditionEvaluationReportLogger : 

Error starting ApplicationContext. To display the condition evaluation report re-run your application with 'debug' enabled.
2023-12-08T10:15:10.155+01:00 ERROR 21496 --- [           main] o.s.boot.SpringApplication               : Application run failed

**To Reproduce**
To use the following libraries and the code snippet below
		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-messaging-servicebus</artifactId>
			<version>7.14.6</version>
		</dependency>

		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-identity</artifactId>
			<version>1.10.3</version>
		</dependency>
		

***Code Snippet***
TokenCredential tokenCredential = new ClientSecretCredentialBuilder()
				.clientId("XXXXXXXXXXX")
				.tenantId("XXXXXXXXXXX")
				.clientSecret("XXXXXXXXXXXXXX")
				.build();

		ServiceBusSenderClient client = new ServiceBusClientBuilder()
				.transportType(AmqpTransportType.AMQP_WEB_SOCKETS)
				.customEndpointAddress("XXXXXXXXXXXXXX")
				.fullyQualifiedNamespace("XXXXXXXXXXXXXX")
				.credential(tokenCredential)
				.sender()
				.topicName("XXXXXXXXXXXXXX").buildClient();

		log.info("Sending message test");
		ServiceBusMessage serviceBusMessage = new ServiceBusMessage("test");
		serviceBusMessage.setSessionId("test");

		client.sendMessage(serviceBusMessage);
		log.info("test message SENT");

		Thread.sleep(10000);

		log.info("Sending message test2");

		ServiceBusMessage serviceBusMessage2 = new ServiceBusMessage("test2");
		serviceBusMessage2.setSessionId("test2");
		client.sendMessage(serviceBusMessage2);

		log.info("test2 message SENT");

		// after waiting for 20000 milliseconds, azure library cannot send anymore any messages
		Thread.sleep(20000);

		log.info("Sending test3");

		ServiceBusMessage serviceBusMessage3 = new ServiceBusMessage("test3");
		serviceBusMessage3.setSessionId("test3");
		client.sendMessage(serviceBusMessage3);

		log.info("test3 message SENT"); // never here

**Expected behavior**

**Setup (please complete the following information):**
 - OS: Windows/Linux
 - IDE: [IntelliJ]
 - Library/Libraries: 
 		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-messaging-servicebus</artifactId>
			<version>7.14.6</version>
		</dependency>

		<dependency>
			<groupId>com.azure</groupId>
			<artifactId>azure-identity</artifactId>
			<version>1.10.3</version>
		</dependency>
		
 - Java version: Java 11, Java 17
 - App Server/Environment: IntelliJ and Docker Swarm cluster
 - Frameworks: Spring Boot

**Comment by conniey** [comment]
Hey. This issue should be resolved in: https://central.sonatype.com/artifact/com.azure/azure-messaging-servicebus/7.15.0/

**Comment by YuliyaMaskvina** [comment]
Hello, thank you for your reply. I tried 7.15.0 and the issue still occur. Could you please assist?
