### ISSUE TITLE
[FEATURE REQ] Missing "additional-spring-configuration-metadata.json" in artifact spring-cloud-azure-starter-appconfiguration-config

### ISSUE THREAD

**Issue by 1goldenboy** [Azure/azure-sdk-for-java#41502]
**Is your feature request related to a problem? Please describe.**
Intellij issues warnings when using the configuration properties available in spring-cloud-azure-starter-appconfiguration-config. It seems that Intellij is unable to pick up AppConfigurationProperties.class in spring-cloud-azure-starter-appconfiguration-config. Instead it picks up AppConfigurationProperties.class in spring-cloud-azure-autoconfigure and marks the other properties as missing. For example considering this configuration in bootstrap.yaml
```
spring:
  cloud:
    azure:
      appconfiguration:
        enabled: true
        stores:
          - endpoint: 'https://my-store-in-azure.azconfig.io'
            feature-flags:
              enabled: true
            selects:
              - keyFilter: '/my-api/'
```
Then "enabled" would not be marked since it is present in both the classes, but "stores" would be marked as missing since its only present in  spring-cloud-azure-starter-appconfiguration-config

**Describe the solution you'd like**
I believe adding the following dependency to the classpath when compiled would solve the issue
```
<dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-configuration-processor</artifactId>
      <optional>true</optional>
</dependency>
```
However, investigating it seems that all properties is defined in spring-cloud-azure-autoconfigure, so perhaps it should be updated there instead?

**Describe alternatives you've considered**
Ignore the warnings 

**Additional context**
None

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Description Added
- [X] Expected solution specified

**Comment by 1goldenboy** [comment]
Also I do believe this is an issue with several other artifacts, for example spring-cloud-azure-feature-management as well

**Comment by Netyyyy** [comment]
@mrm9084 please help take a look

**Comment by 1goldenboy** [comment]
Some additional context and pictures: 

Here is the warning Intellj issues:

![image](https://github.com/user-attachments/assets/08cef030-d919-4bb4-8b4d-db2272e1aa98)
 
Property 'enabled' is recognized by Intelij, but points to an unexpected class ->  com.azure.spring.cloud.autoconfigure.implementation.properties.core.AbstractAzureServiceConfigurationProperties

![image](https://github.com/user-attachments/assets/ce5431bd-56af-4767-9784-cc636f4cee69)

Properties 'endpoint', 'keyFilter' and 'labelFilter' is not recognized

The expected class is in the azure appconfiguration artifact -> com.azure.spring.cloud.appconfiguration.config.implementation.properties.AppConfigurationProperties

![image](https://github.com/user-attachments/assets/af603445-5ec9-427a-8f86-564f457e4aba)

As mentioned I do believe this is because the azure appconfiguration artifact is missing a spring-configuration-metadata.json-file which 'spring-boot-configuration-processor' would generate on compile

![image](https://github.com/user-attachments/assets/0abfb2ba-0181-490a-80d7-d66a59f01683)

**Comment by mrm9084** [comment]
@1goldenboy, this should be fixed and will be part of the next release which should be in the next week or so. I'll post here when it's out.

**Comment by 1goldenboy** [comment]
Just checked it out. It looks great!

I found one minor thing. LabelFilter is still getting a warning since it only has a setter and not an equivalent getter (ref: https://github.com/spring-projects/sts4/issues/1180). I think changing this would require to add equivalent getter `public String getLabelFilter() ` both in FeatureFlagKeyValueSelector.java and AppConfigurationKeyValueSelector.java. 

All remaining properties here are working fine! https://github.com/Azure/azure-sdk-for-java/tree/spring-cloud-azure-appconfiguration-config_5.16.0/sdk/spring/spring-cloud-azure-starter-appconfiguration-config

**Comment by 1goldenboy** [comment]
Closing this as the original request has been resolved. Thank you!
