### ISSUE TITLE
[BUG] [1] [parallel-2] [] [reactor.util.Loggers$Slf4JLogger] - Operator called default onErrorDropped reactor.core.Exceptions$ErrorCallbackNotImplemented: java.lang.NullPointerException Caused by: java.lang.NullPointerException

### ISSUE THREAD

**Issue by dineshlalwani** [Azure/azure-sdk-for-java#42987]
**Describe the bug**
We're using streamBridge.send(bindingName, MessageBuilder.withPayload(payload).build()) to send messages in ASB Queues, it is maximizing our CPU usage and ultimately crashing the service because of [reactor-executor-XXXX] thread leaks.

***Exception or Stack Trace***
```
[2024-11-11 08:39:31.031] [INFO ] [1] [reactor-executor-1854] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"onSessionRemoteClose","connectionId":"MF_6adc03_1731309919739","errorCondition":"amqp:connection:forced","errorDescription":"The connection was closed by container '4fc9165857464070a1d8ebe127ce71d8_G2' because it did not have any active links in the past 300000 milliseconds. TrackingId:4fc9165857464070a1d8ebe127ce71d8_G2, SystemTracker:gateway5, Timestamp:2024-11-11T08:39:31","sessionName":"session_Name"}
[2024-11-11 08:39:31.031] [INFO ] [1] [reactor-executor-1854] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"onSessionRemoteClose closing a local session.","connectionId":"MF_6adc03_1731309919739","errorCondition":"amqp:connection:forced","errorDescription":"The connection was closed by container '4fc9165857464070a1d8ebe127ce71d8_G2' because it did not have any active links in the past 300000 milliseconds. TrackingId:4fc9165857464070a1d8ebe127ce71d8_G2, SystemTracker:gateway5, Timestamp:2024-11-11T08:39:31","sessionName":"session_Name"}
[2024-11-11 08:39:31.031] [ERROR] [1] [reactor-executor-1854] [] [reactor.util.Loggers$Slf4JLogger] - Operator called default onErrorDropped
reactor.core.Exceptions$ErrorCallbackNotImplemented: com.azure.core.amqp.exception.AmqpException: onSessionRemoteClose connectionId[MF_6adc03_1731309919739], entityName[entity_name] condition[Error{condition=amqp:connection:forced, description='The connection was closed by container '4fc9165857464070a1d8ebe127ce71d8_G2' because it did not have any active links in the past 300000 milliseconds. TrackingId:4fc9165857464070a1d8ebe127ce71d8_G2, SystemTracker:gateway5, Timestamp:2024-11-11T08:39:31', info=null}], errorContext[NAMESPACE: host_name. ERROR CONTEXT: N/A, PATH: entity_name]
Caused by: com.azure.core.amqp.exception.AmqpException: onSessionRemoteClose connectionId[MF_6adc03_1731309919739], entityName[entity_name] condition[Error{condition=amqp:connection:forced, description='The connection was closed by container '4fc9165857464070a1d8ebe127ce71d8_G2' because it did not have any active links in the past 300000 milliseconds. TrackingId:4fc9165857464070a1d8ebe127ce71d8_G2, SystemTracker:gateway5, Timestamp:2024-11-11T08:39:31', info=null}], errorContext[NAMESPACE: host_name. ERROR CONTEXT: N/A, PATH: entity_name]
	at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:85) ~[azure-core-amqp-2.8.8.jar!/:2.8.8]
	at com.azure.core.amqp.implementation.handler.SessionHandler.onSessionRemoteClose(SessionHandler.java:136) ~[azure-core-amqp-2.8.8.jar!/:2.8.8]
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:152) ~[proton-j-0.33.8.jar!/:?]
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) ~[proton-j-0.33.8.jar!/:?]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324) ~[proton-j-0.33.8.jar!/:?]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291) ~[proton-j-0.33.8.jar!/:?]
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:91) ~[azure-core-amqp-2.8.8.jar!/:2.8.8]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) [reactor-core-3.5.7.jar!/:3.5.7]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) [reactor-core-3.5.7.jar!/:3.5.7]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[2024-11-11 08:39:31.031] [INFO ] [1] [reactor-executor-1854] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"Error occurred. Removing and disposing session","exception":"onSessionRemoteClose connectionId[MF_6adc03_1731309919739], entityName[entity_name] condition[Error{condition=amqp:connection:forced, description='The connection was closed by container '4fc9165857464070a1d8ebe127ce71d8_G2' because it did not have any active links in the past 300000 milliseconds. TrackingId:4fc9165857464070a1d8ebe127ce71d8_G2, SystemTracker:gateway5, Timestamp:2024-11-11T08:39:31', info=null}], errorContext[NAMESPACE: host_name. ERROR CONTEXT: N/A, PATH: entity_name]","connectionId":"MF_6adc03_1731309919739","sessionName":"session_Name"}
[2024-11-11 08:39:31.031] [INFO ] [1] [reactor-executor-1854] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"onLinkRemoteClose","connectionId":"MF_6adc03_1731309919739","errorCondition":"amqp:connection:forced","errorDescription":"The connection was closed by container '4fc9165857464070a1d8ebe127ce71d8_G2' because it did not have any active links in the past 300000 milliseconds. TrackingId:4fc9165857464070a1d8ebe127ce71d8_G2, SystemTracker:gateway5, Timestamp:2024-11-11T08:39:31","linkName":"cbs:sender","entityPath":"$cbs"}
[2024-11-11 08:39:31.031] [INFO ] [1] [reactor-executor-1854] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"Local link state is not closed.","connectionId":"MF_6adc03_1731309919739","linkName":"cbs:sender","entityPath":"$cbs","state":"ACTIVE"}
[2024-11-11 08:39:31.031] [WARN ] [1] [reactor-executor-1854] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"Error in SendLinkHandler. Disposing unconfirmed sends.","exception":"The connection was closed by container '4fc9165857464070a1d8ebe127ce71d8_G2' because it did not have any active links in the past 300000 milliseconds. TrackingId:4fc9165857464070a1d8ebe127ce71d8_G2, SystemTracker:gateway5, Timestamp:2024-11-11T08:39:31, errorContext[NAMESPACE: host_name. ERROR CONTEXT: N/A, PATH: $cbs, REFERENCE_ID: cbs:sender, LINK_CREDIT: 97]","connectionId":"MF_6adc03_1731309919739","linkName":"cbs"}
[2024-11-11 08:39:31.031] [INFO ] [1] [reactor-executor-1854] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"Transient error occurred. Retrying.","exception":"The connection was closed by container '4fc9165857464070a1d8ebe127ce71d8_G2' because it did not have any active links in the past 300000 milliseconds. TrackingId:4fc9165857464070a1d8ebe127ce71d8_G2, SystemTracker:gateway5, Timestamp:2024-11-11T08:39:31, errorContext[NAMESPACE: host_name. ERROR CONTEXT: N/A, PATH: $cbs, REFERENCE_ID: cbs:sender, LINK_CREDIT: 97]","connectionId":"MF_6adc03_1731309919739","entityPath":"$cbs","tryCount":0,"interval_ms":4511}
[2024-11-11 08:39:31.031] [INFO ] [1] [reactor-executor-1854] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"onLinkRemoteClose","connectionId":"MF_6adc03_1731309919739","errorCondition":"amqp:connection:forced","errorDescription":"The connection was closed by container '4fc9165857464070a1d8ebe127ce71d8_G2' because it did not have any active links in the past 300000 milliseconds. TrackingId:4fc9165857464070a1d8ebe127ce71d8_G2, SystemTracker:gateway5, Timestamp:2024-11-11T08:39:31","linkName":"cbs:receiver","entityPath":"$cbs"}
[2024-11-11 08:39:31.031] [INFO ] [1] [reactor-executor-1854] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"Local link state is not closed.","connectionId":"MF_6adc03_1731309919739","linkName":"cbs:receiver","entityPath":"$cbs","state":"ACTIVE"}
[2024-11-11 08:39:31.031] [INFO ] [1] [reactor-executor-1854] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"onSessionRemoteClose","connectionId":"MF_6adc03_1731309919739","errorCondition":"amqp:connection:forced","errorDescription":"The connection was closed by container '4fc9165857464070a1d8ebe127ce71d8_G2' because it did not have any active links in the past 300000 milliseconds. TrackingId:4fc9165857464070a1d8ebe127ce71d8_G2, SystemTracker:gateway5, Timestamp:2024-11-11T08:39:31","sessionName":"xyz-session"}
[2024-11-11 08:39:31.031] [INFO ] [1] [reactor-executor-1854] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"onSessionRemoteClose closing a local session.","connectionId":"MF_6adc03_1731309919739","errorCondition":"amqp:connection:forced","errorDescription":"The connection was closed by container '4fc9165857464070a1d8ebe127ce71d8_G2' because it did not have any active links in the past 300000 milliseconds. TrackingId:4fc9165857464070a1d8ebe127ce71d8_G2, SystemTracker:gateway5, Timestamp:2024-11-11T08:39:31","sessionName":"xyz-session"}
[2024-11-11 08:39:31.031] [ERROR] [1] [reactor-executor-1854] [] [reactor.util.Loggers$Slf4JLogger] - Operator called default onErrorDropped
reactor.core.Exceptions$ErrorCallbackNotImplemented: com.azure.core.amqp.exception.AmqpException: onSessionRemoteClose connectionId[MF_6adc03_1731309919739], entityName[cbs-session] condition[Error{condition=amqp:connection:forced, description='The connection was closed by container '4fc9165857464070a1d8ebe127ce71d8_G2' because it did not have any active links in the past 300000 milliseconds. TrackingId:4fc9165857464070a1d8ebe127ce71d8_G2, SystemTracker:gateway5, Timestamp:2024-11-11T08:39:31', info=null}], errorContext[NAMESPACE: host_name. ERROR CONTEXT: N/A, PATH: cbs-session]
Caused by: com.azure.core.amqp.exception.AmqpException: onSessionRemoteClose connectionId[MF_6adc03_1731309919739], entityName[cbs-session] condition[Error{condition=amqp:connection:forced, description='The connection was closed by container '4fc9165857464070a1d8ebe127ce71d8_G2' because it did not have any active links in the past 300000 milliseconds. TrackingId:4fc9165857464070a1d8ebe127ce71d8_G2, SystemTracker:gateway5, Timestamp:2024-11-11T08:39:31', info=null}], errorContext[NAMESPACE: host_name. ERROR CONTEXT: N/A, PATH: cbs-session]
	at com.azure.core.amqp.implementation.ExceptionUtil.toException(ExceptionUtil.java:85) ~[azure-core-amqp-2.8.8.jar!/:2.8.8]
	at com.azure.core.amqp.implementation.handler.SessionHandler.onSessionRemoteClose(SessionHandler.java:136) ~[azure-core-amqp-2.8.8.jar!/:2.8.8]
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:152) ~[proton-j-0.33.8.jar!/:?]
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) ~[proton-j-0.33.8.jar!/:?]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:324) ~[proton-j-0.33.8.jar!/:?]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:291) ~[proton-j-0.33.8.jar!/:?]
	at com.azure.core.amqp.implementation.ReactorExecutor.run(ReactorExecutor.java:91) ~[azure-core-amqp-2.8.8.jar!/:2.8.8]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68) [reactor-core-3.5.7.jar!/:3.5.7]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28) [reactor-core-3.5.7.jar!/:3.5.7]
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
[2024-11-11 08:39:31.031] [INFO ] [1] [reactor-executor-1854] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"Error occurred. Removing and disposing session","exception":"onSessionRemoteClose connectionId[MF_6adc03_1731309919739], entityName[cbs-session] condition[Error{condition=amqp:connection:forced, description='The connection was closed by container '4fc9165857464070a1d8ebe127ce71d8_G2' because it did not have any active links in the past 300000 milliseconds. TrackingId:4fc9165857464070a1d8ebe127ce71d8_G2, SystemTracker:gateway5, Timestamp:2024-11-11T08:39:31', info=null}], errorContext[NAMESPACE: host_name. ERROR CONTEXT: N/A, PATH: cbs-session]","connectionId":"MF_6adc03_1731309919739","sessionName":"xyz-session"}
[2024-11-11 08:39:31.031] [INFO ] [1] [reactor-executor-1854] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"onConnectionRemoteClose","connectionId":"MF_6adc03_1731309919739","errorCondition":"amqp:connection:forced","errorDescription":"The connection was closed by container '4fc9165857464070a1d8ebe127ce71d8_G2' because it did not have any active links in the past 300000 milliseconds. TrackingId:4fc9165857464070a1d8ebe127ce71d8_G2, SystemTracker:gateway5, Timestamp:2024-11-11T08:39:31","hostName":"host_name"}
[2024-11-11 08:39:31.031] [INFO ] [1] [reactor-executor-1854] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"onTransportClosed","connectionId":"MF_6adc03_1731309919739","hostName":"host_name"}
[2024-11-11 08:39:31.031] [INFO ] [1] [reactor-executor-1854] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"onTransportClosed","connectionId":"MF_6adc03_1731309919739","hostName":"host_name"}
[2024-11-11 08:39:31.031] [INFO ] [1] [reactor-executor-1854] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"onConnectionLocalClose","connectionId":"MF_6adc03_1731309919739","hostName":"host_name"}
[2024-11-11 08:39:31.031] [INFO ] [1] [reactor-executor-1854] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"onConnectionUnbound","connectionId":"MF_6adc03_1731309919739","hostName":"host_name","state":"CLOSED","remoteState":"CLOSED"}
[2024-11-11 08:39:31.031] [INFO ] [1] [reactor-executor-1854] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"Disposing of ReactorConnection.","connectionId":"MF_6adc03_1731309919739","isTransient":false,"isInitiatedByClient":false,"shutdownMessage":"Connection handler closed."}
[2024-11-11 08:39:31.031] [INFO ] [1] [reactor-executor-1854] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"Channel is closed. Requesting upstream.","entityPath":"N/A"}
[2024-11-11 08:39:31.031] [INFO ] [1] [reactor-executor-1854] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"Connection not requested, yet. Requesting one.","entityPath":"N/A"}
[2024-11-11 08:39:31.031] [INFO ] [1] [reactor-executor-1854] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"Setting next AMQP channel.","entityPath":"N/A"}
[2024-11-11 08:39:31.031] [INFO ] [1] [reactor-executor-1854] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"onLinkFinal","connectionId":"MF_6adc03_1731309919739","linkName":"entity_nameentity_name","entityPath":"entity_name"}
[2024-11-11 08:39:31.031] [INFO ] [1] [reactor-executor-1854] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"onLinkFinal","connectionId":"MF_6adc03_1731309919739","linkName":"entity_nameentity_name","entityPath":"entity_name"}
[2024-11-11 08:39:31.031] [INFO ] [1] [reactor-executor-1854] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"onSessionFinal.","connectionId":"MF_6adc03_1731309919739","errorCondition":"amqp:connection:forced","errorDescription":"The connection was closed by container '4fc9165857464070a1d8ebe127ce71d8_G2' because it did not have any active links in the past 300000 milliseconds. TrackingId:4fc9165857464070a1d8ebe127ce71d8_G2, SystemTracker:gateway5, Timestamp:2024-11-11T08:39:31","sessionName":"session_Name"}
[2024-11-11 08:39:31.031] [INFO ] [1] [reactor-executor-1854] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"onLinkFinal","connectionId":"MF_6adc03_1731309919739","linkName":"cbs:sender","entityPath":"$cbs"}
[2024-11-11 08:39:31.031] [INFO ] [1] [reactor-executor-1854] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"onLinkFinal","connectionId":"MF_6adc03_1731309919739","linkName":"cbs:receiver","entityPath":"$cbs"}
[2024-11-11 08:39:31.031] [INFO ] [1] [reactor-executor-1854] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"onSessionFinal.","connectionId":"MF_6adc03_1731309919739","errorCondition":"amqp:connection:forced","errorDescription":"The connection was closed by container '4fc9165857464070a1d8ebe127ce71d8_G2' because it did not have any active links in the past 300000 milliseconds. TrackingId:4fc9165857464070a1d8ebe127ce71d8_G2, SystemTracker:gateway5, Timestamp:2024-11-11T08:39:31","sessionName":"xyz-session"}
[2024-11-11 08:39:31.031] [INFO ] [1] [reactor-executor-1854] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"onConnectionFinal","connectionId":"MF_6adc03_1731309919739","hostName":"host_name"}

```
***Code Snippet***
We're using **StreamBridge** to send message over ASB Queues, whenever it comes in idle state we receive The connection was closed by container 'container_name' because it did not have any active links in the past 300000 milliseconds. TrackingId:tracking_id, SystemTracker:System_Tracker, Timestamp:2024-11-11T08:39:31', info=null

**Expected behavior**
It should not throw NPE and prevents thread leak

**Setup (please complete the following information):**
 - OS: running on K8s
 - IDE: running on K8s
 - Library/Libraries: com.azure.spring:spring-cloud-azure-stream-binder-servicebus:5.5.0 (groupId:artifactId:version)]
 - Java version: 17 
 - App Server/Environment: Tomcat
 - Frameworks: Spring Boot

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by dineshlalwani** [comment]
Dependencies 

 +- com.azure.spring:spring-cloud-azure-stream-binder-servicebus:jar:5.5.0:compile
[INFO] |  +- com.azure.spring:spring-cloud-azure-stream-binder-servicebus-core:jar:5.5.0:compile
[INFO] |  |  +- org.springframework.cloud:spring-cloud-stream:jar:4.0.4:compile
[INFO] |  |  |  +- org.springframework.boot:spring-boot-starter-validation:jar:3.1.1:compile
[INFO] |  |  |  |  \- org.hibernate.validator:hibernate-validator:jar:8.0.0.Final:compile
[INFO] |  |  |  |     +- org.jboss.logging:jboss-logging:jar:3.5.1.Final:compile
[INFO] |  |  |  |     \- com.fasterxml:classmate:jar:1.5.1:compile
[INFO] |  |  |  +- org.springframework:spring-messaging:jar:6.0.10:compile
[INFO] |  |  |  +- org.springframework.integration:spring-integration-core:jar:6.1.1:compile
[INFO] |  |  |  +- org.springframework.integration:spring-integration-jmx:jar:6.1.1:compile
[INFO] |  |  |  +- org.springframework.cloud:spring-cloud-function-context:jar:4.1.3:compile
[INFO] |  |  |  |  +- net.jodah:typetools:jar:0.6.2:compile
[INFO] |  |  |  |  \- org.springframework.cloud:spring-cloud-function-core:jar:4.1.3:compile
[INFO] |  |  |  \- org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:1.8.22:compile
[INFO] |  |  |     \- org.jetbrains.kotlin:kotlin-stdlib-jdk7:jar:1.8.22:compile
[INFO] |  |  +- com.azure.spring:spring-integration-azure-servicebus:jar:5.5.0:compile
[INFO] |  |  |  +- com.azure.spring:spring-integration-azure-core:jar:5.5.0:compile
[INFO] |  |  |  |  \- com.azure.spring:spring-messaging-azure:jar:5.5.0:compile
[INFO] |  |  |  \- com.azure.spring:spring-messaging-azure-servicebus:jar:5.5.0:compile
[INFO] |  |  \- com.azure:azure-messaging-servicebus:jar:7.14.3:compile
[INFO] |  |     \- com.azure:azure-core-amqp:jar:2.8.8:compile
[INFO] |  |        +- com.microsoft.azure:qpid-proton-j-extensions:jar:1.2.4:compile
[INFO] |  |        \- org.apache.qpid:proton-j:jar:0.33.8:compile
[

**Comment by alzimmermsft** [comment]
Thank you for filing this @dineshlalwani.

@anuchandy, @conniey could you check if this is an issue from `azure-core-amqp` or an issue in the Spring binder?

**Comment by anuchandy** [comment]
Hello @dineshlalwani, thanks for reaching out.

The version "azure-messaging-servicebus:jar:7.14.3" has a thread leak problem, this issue likely began after a broker timeout change, which older library versions cannot handle. 

The issue is fixed in "azure-messaging-servicebus:jar:7.17.5".
 
Could you update your application to use "spring-cloud-azure-stream-binder-servicebus:5.18.0", which includes "azure-messaging-servicebus:7.17.5" as a transitive dependency? Avoid combining "spring-cloud-azure-stream-binder-servicebus:jar:5.5.0" with "azure-messaging-servicebus:jar:7.17.5" explicitly, as it causes runtime conflicts.

After updating to "spring-cloud-azure-stream-binder-servicebus:5.18.0" (and removing any explicit version override of "azure-messaging-servicebus"), set the system property "com.azure.core.amqp.cache" to _true_. Without this setting, the app can still experience the thread leak. Although I don't have expertise in the Spring ecosystem, I assume you know how set a system property in a way that Spring system make it available for the runtime so SDK can pick it up.

Sorry for the inconvenience, but the need to set the setting "com.azure.core.amqp.cache" will be removed in the November 2024 release. The spring team is expected to release stream binder by the last week of November or early December.

**Comment by dineshlalwani** [comment]
@anuchandy I'm trying this way, since by setting "com.azure.core.amqp.cache" System Property was not working.
```
<dependency>
            <groupId>com.azure.spring</groupId>
            <artifactId>spring-cloud-azure-stream-binder-servicebus</artifactId>
            <version>5.18.0</version>
            <exclusions>
                <exclusion>
                    <groupId>com.azure</groupId>
                    <artifactId>azure-messaging-servicebus</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>applicationinsights-runtime-attach</artifactId>
            <version>3.4.10</version>
        </dependency>
        <dependency>
            <groupId>com.azure</groupId>
            <artifactId>azure-messaging-servicebus</artifactId>
            <version>7.17.6</version>
        </dependency>
```
After this I didn't see any exception like this```
 [reactor.util.Loggers$Slf4JLogger] - Operator called default onErrorDropped
reactor.core.Exceptions$ErrorCallbackNotImplemented: com.azure.core.amqp.exception.AmqpException: onSessionRemoteClose connectionId[MF_6adc03_1731309919739], entityName[entity_name] condition[Error{condition=amqp:connection:forced, description='The connection was closed by container '4fc9165857464070a1d8ebe127ce71d8_G2' because it did not have any active links in the past 300000 milliseconds. TrackingId:4fc9165857464070a1d8ebe127ce71d8_G2, SystemTracker:gateway5, Timestamp:2024-11-11T08:39:31', info=null}], errorContext[NAMESPACE: host_name. ERROR CONTEXT: N/A, PATH: entity_name]
Caused by: com.azure.core.amqp.exception.AmqpException: onSessionRemoteClose connectionId[MF_6adc03_1731309919739], entityName[entity_name] condition[Error{condition=amqp:connection:forced, description='The connection was closed by container '4fc9165857464070a1d8ebe127ce71d8_G2' because it did not have any active links in the past 300000 milliseconds. TrackingId:4fc9165857464070a1d8ebe127ce71d8_G2, SystemTracker:gateway5, Timestamp:2024-11-11T08:39:31', info=null}], errorContext[NAMESPACE: host_name. ERROR CONTEXT: N/A, PATH: entity_name]

```
But I'm still not sure about the thread leak and why is it happening?

**Comment by anuchandy** [comment]
Hi @dineshlalwani, thanks for the response. To help troubleshooting, could you please share the following:

1.  output of `mvn dependency:tree`
2.  "Azure SDK" "DEBUG" logs for 20 minutes since the start of the application using ASB.

Details on how to enable "Azure SDK" logging can be found [here](https://learn.microsoft.com/en-us/azure/developer/java/sdk/troubleshooting-messaging-service-bus-overview#enable-and-configure-logging), including reference to log configurations files with filters. Note that, we "don't" need low level logs (via PN_TRACE_FRM=1) but only the "Azure SDK" logs.

**Comment by dineshlalwani** [comment]
Hi @anuchandy,

1. **Dependency Tree**

```

 +- com.azure.spring:spring-cloud-azure-stream-binder-servicebus:jar:5.18.0:compile
[INFO] |  +- com.azure.spring:spring-cloud-azure-stream-binder-servicebus-core:jar:5.18.0:compile
[INFO] |  |  +- org.springframework.cloud:spring-cloud-stream:jar:4.1.3:compile
[INFO] |  |  |  +- org.springframework.boot:spring-boot-starter-validation:jar:3.1.1:compile
[INFO] |  |  |  |  \- org.hibernate.validator:hibernate-validator:jar:8.0.0.Final:compile
[INFO] |  |  |  |     +- org.jboss.logging:jboss-logging:jar:3.5.1.Final:compile
[INFO] |  |  |  |     \- com.fasterxml:classmate:jar:1.5.1:compile
[INFO] |  |  |  +- org.springframework:spring-messaging:jar:6.0.10:compile
[INFO] |  |  |  +- org.springframework.integration:spring-integration-core:jar:6.1.1:compile
[INFO] |  |  |  +- org.springframework.integration:spring-integration-jmx:jar:6.1.1:compile
[INFO] |  |  |  +- org.springframework.cloud:spring-cloud-function-context:jar:4.1.3:compile
[INFO] |  |  |  |  +- net.jodah:typetools:jar:0.6.2:compile
[INFO] |  |  |  |  \- org.springframework.cloud:spring-cloud-function-core:jar:4.1.3:compile
[INFO] |  |  |  \- org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:1.8.22:compile
[INFO] |  |  |     \- org.jetbrains.kotlin:kotlin-stdlib-jdk7:jar:1.8.22:compile
[INFO] |  |  \- com.azure.spring:spring-integration-azure-servicebus:jar:5.18.0:compile
[INFO] |  |     +- com.azure.spring:spring-integration-azure-core:jar:5.18.0:compile
[INFO] |  |     |  \- com.azure.spring:spring-messaging-azure:jar:5.18.0:compile
[INFO] |  |     \- com.azure.spring:spring-messaging-azure-servicebus:jar:5.18.0:compile
[INFO] |  +- com.azure.spring:spring-cloud-azure-autoconfigure:jar:5.18.0:compile
[INFO] |  |  +- com.azure.spring:spring-cloud-azure-service:jar:5.18.0:compile
[INFO] |  |  \- jakarta.validation:jakarta.validation-api:jar:3.0.2:compile
[INFO] |  \- com.azure.spring:spring-cloud-azure-resourcemanager:jar:5.18.0:compile
[INFO] |     +- com.azure.spring:spring-cloud-azure-core:jar:5.18.0:compile
[INFO] |     |  \- com.azure:azure-core-management:jar:1.15.4:compile
[INFO] |     \- com.azure.resourcemanager:azure-resourcemanager:jar:2.44.0:compile
[INFO] |        +- com.azure.resourcemanager:azure-resourcemanager-resources:jar:2.44.0:compile
[INFO] |        +- com.azure.resourcemanager:azure-resourcemanager-storage:jar:2.44.0:compile
[INFO] |        +- com.azure.resourcemanager:azure-resourcemanager-compute:jar:2.44.0:compile
[INFO] |        +- com.azure.resourcemanager:azure-resourcemanager-network:jar:2.44.0:compile
[INFO] |        +- com.azure.resourcemanager:azure-resourcemanager-keyvault:jar:2.44.0:compile
[INFO] |        |  +- com.azure:azure-security-keyvault-keys:jar:4.9.0:compile
[INFO] |        |  \- com.azure:azure-security-keyvault-secrets:jar:4.9.0:compile
[INFO] |        +- com.azure.resourcemanager:azure-resourcemanager-msi:jar:2.44.0:compile
[INFO] |        +- com.azure.resourcemanager:azure-resourcemanager-sql:jar:2.44.0:compile
[INFO] |        +- com.azure.resourcemanager:azure-resourcemanager-authorization:jar:2.44.0:compile
[INFO] |        +- com.azure.resourcemanager:azure-resourcemanager-appservice:jar:2.44.0:compile
[INFO] |        +- com.azure.resourcemanager:azure-resourcemanager-cosmos:jar:2.44.0:compile
[INFO] |        +- com.azure.resourcemanager:azure-resourcemanager-containerservice:jar:2.44.0:compile
[INFO] |        +- com.azure.resourcemanager:azure-resourcemanager-monitor:jar:2.44.0:compile
[INFO] |        +- com.azure.resourcemanager:azure-resourcemanager-containerregistry:jar:2.44.0:compile
[INFO] |        +- com.azure.resourcemanager:azure-resourcemanager-dns:jar:2.44.0:compile
[INFO] |        +- com.azure.resourcemanager:azure-resourcemanager-appplatform:jar:2.44.0:compile
[INFO] |        |  \- com.azure:azure-storage-file-share:jar:12.24.0:compile
[INFO] |        +- com.azure.resourcemanager:azure-resourcemanager-containerinstance:jar:2.44.0:compile
[INFO] |        +- com.azure.resourcemanager:azure-resourcemanager-privatedns:jar:2.44.0:compile
[INFO] |        +- com.azure.resourcemanager:azure-resourcemanager-redis:jar:2.44.0:compile
[INFO] |        +- com.azure.resourcemanager:azure-resourcemanager-eventhubs:jar:2.44.0:compile
[INFO] |        +- com.azure.resourcemanager:azure-resourcemanager-trafficmanager:jar:2.44.0:compile
[INFO] |        +- com.azure.resourcemanager:azure-resourcemanager-servicebus:jar:2.44.0:compile
[INFO] |        +- com.azure.resourcemanager:azure-resourcemanager-cdn:jar:2.44.0:compile
[INFO] |        \- com.azure.resourcemanager:azure-resourcemanager-search:jar:2.44.0:compile
[INFO] +- com.microsoft.azure:applicationinsights-runtime-attach:jar:3.4.10:compile
[INFO] |  \- io.opentelemetry.contrib:opentelemetry-runtime-attach-core:jar:1.18.0-alpha:runtime
[INFO] \- com.azure:azure-messaging-servicebus:jar:7.17.6:compile
[INFO]    +- com.azure:azure-core:jar:1.54.0:compile
[INFO]    |  +- com.azure:azure-json:jar:1.3.0:compile
[INFO]    |  \- io.projectreactor:reactor-core:jar:3.5.7:compile
[INFO]    |     \- org.reactivestreams:reactive-streams:jar:1.0.4:compile
[INFO]    +- com.azure:azure-xml:jar:1.1.0:compile
[INFO]    +- com.azure:azure-core-amqp:jar:2.9.11:compile
[INFO]    |  +- com.microsoft.azure:qpid-proton-j-extensions:jar:1.2.5:compile
[INFO]    |  \- org.apache.qpid:proton-j:jar:0.34.1:compile
[INFO]    \- com.azure:azure-core-http-netty:jar:1.15.6:compile
[INFO]       +- io.netty:netty-handler:jar:4.1.94.Final:compile
[INFO]       |  +- io.netty:netty-resolver:jar:4.1.94.Final:compile
[INFO]       |  \- io.netty:netty-transport:jar:4.1.94.Final:compile
[INFO]       +- io.netty:netty-handler-proxy:jar:4.1.94.Final:compile
[INFO]       |  \- io.netty:netty-codec-socks:jar:4.1.94.Final:compile
[INFO]       +- io.netty:netty-buffer:jar:4.1.94.Final:compile
[INFO]       +- io.netty:netty-codec:jar:4.1.94.Final:compile
[INFO]       +- io.netty:netty-codec-http:jar:4.1.108.Final:compile
[INFO]       +- io.netty:netty-codec-http2:jar:4.1.108.Final:compile
[INFO]       +- io.netty:netty-transport-native-unix-common:jar:4.1.94.Final:compile
[INFO]       +- io.netty:netty-transport-native-epoll:jar:linux-x86_64:4.1.94.Final:compile
[INFO]       |  \- io.netty:netty-transport-classes-epoll:jar:4.1.94.Final:compile
[INFO]       +- io.netty:netty-transport-native-kqueue:jar:osx-x86_64:4.1.94.Final:compile
[INFO]       |  \- io.netty:netty-transport-classes-kqueue:jar:4.1.94.Final:compile
[INFO]       +- io.netty:netty-tcnative-boringssl-static:jar:2.0.61.Final:compile
[INFO]       |  +- io.netty:netty-tcnative-classes:jar:2.0.61.Final:compile
[INFO]       |  +- io.netty:netty-tcnative-boringssl-static:jar:linux-x86_64:2.0.61.Final:compile
[INFO]       |  +- io.netty:netty-tcnative-boringssl-static:jar:linux-aarch_64:2.0.61.Final:compile
[INFO]       |  +- io.netty:netty-tcnative-boringssl-static:jar:osx-x86_64:2.0.61.Final:compile
[INFO]       |  +- io.netty:netty-tcnative-boringssl-static:jar:osx-aarch_64:2.0.61.Final:compile
[INFO]       |  \- io.netty:netty-tcnative-boringssl-static:jar:windows-x86_64:2.0.61.Final:compile
[INFO]       +- io.projectreactor.netty:reactor-netty-http:jar:1.1.17:compile
[INFO]       |  +- io.netty:netty-resolver-dns:jar:4.1.94.Final:compile
[INFO]       |  |  \- io.netty:netty-codec-dns:jar:4.1.94.Final:compile
[INFO]       |  +- io.netty:netty-resolver-dns-native-macos:jar:osx-x86_64:4.1.94.Final:compile
[INFO]       |  |  \- io.netty:netty-resolver-dns-classes-macos:jar:4.1.94.Final:compile
[INFO]       |  \- io.projectreactor.netty:reactor-netty-core:jar:1.1.17:compile
[INFO]       \- io.netty:netty-common:jar:4.1.94.Final:compile
```


3. Azure Logs:(Let me know if this works for you)

```
[2024-11-24 09:24:15.015] [INFO ] [1] [reactor-executor-367] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"onSessionRemoteClose","connectionId":"MF_473fc2_1732438874867","errorCondition":"amqp:connection:forced","errorDescription":"The connection was closed by container '202d78bdc70b4e5a81578c17a4381207_G16' because it did not have any active links in the past 300000 milliseconds. TrackingId:202d78bdc70b4e5a81578c17a4381207_G16, SystemTracker:gateway10, Timestamp:2024-11-24T09:24:15","sessionName":"session_name_dummy","sessionId":"H_14c8b1_1732438874918"}
[2024-11-24 09:24:15.015] [INFO ] [1] [reactor-executor-367] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"onSessionRemoteClose closing a local session.","connectionId":"MF_473fc2_1732438874867","errorCondition":"amqp:connection:forced","errorDescription":"The connection was closed by container '202d78bdc70b4e5a81578c17a4381207_G16' because it did not have any active links in the past 300000 milliseconds. TrackingId:202d78bdc70b4e5a81578c17a4381207_G16, SystemTracker:gateway10, Timestamp:2024-11-24T09:24:15","sessionName":"session_name_dummy"}
[2024-11-24 09:24:15.015] [WARN ] [1] [reactor-executor-367] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"Session endpoint state signaled error.","exception":"onSessionRemoteClose connectionId[MF_473fc2_1732438874867], entityName[session_name_dummy] condition[Error{condition=amqp:connection:forced, description='The connection was closed by container '202d78bdc70b4e5a81578c17a4381207_G16' because it did not have any active links in the past 300000 milliseconds. TrackingId:202d78bdc70b4e5a81578c17a4381207_G16, SystemTracker:gateway10, Timestamp:2024-11-24T09:24:15', info=null}], errorContext[NAMESPACE: name_dummyservicebus.windows.net. ERROR CONTEXT: N/A, PATH: session_name_dummy]","connectionId":"MF_473fc2_1732438874867","sessionName":"session_name_dummy","sessionId":"H_14c8b1_1732438874918"}
[2024-11-24 09:24:15.015] [INFO ] [1] [reactor-executor-367] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"Evicting session terminated with error.","exception":"onSessionRemoteClose connectionId[MF_473fc2_1732438874867], entityName[session_name_dummy] condition[Error{condition=amqp:connection:forced, description='The connection was closed by container '202d78bdc70b4e5a81578c17a4381207_G16' because it did not have any active links in the past 300000 milliseconds. TrackingId:202d78bdc70b4e5a81578c17a4381207_G16, SystemTracker:gateway10, Timestamp:2024-11-24T09:24:15', info=null}], errorContext[NAMESPACE: name_dummyservicebus.windows.net. ERROR CONTEXT: N/A, PATH: session_name_dummy]","connectionId":"MF_473fc2_1732438874867","sessionName":"session_name_dummy","sessionId":"H_14c8b1_1732438874918"}
[2024-11-24 09:24:15.015] [INFO ] [1] [reactor-executor-367] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"session disposal is completed","connectionId":"MF_473fc2_1732438874867","sessionName":"session_name_dummy","sessionId":"H_14c8b1_1732438874918"}
[2024-11-24 09:24:15.015] [INFO ] [1] [reactor-executor-367] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"onLinkRemoteClose","connectionId":"MF_473fc2_1732438874867","errorCondition":"amqp:connection:forced","errorDescription":"The connection was closed by container '202d78bdc70b4e5a81578c17a4381207_G16' because it did not have any active links in the past 300000 milliseconds. TrackingId:202d78bdc70b4e5a81578c17a4381207_G16, SystemTracker:gateway10, Timestamp:2024-11-24T09:24:15","linkName":"cbs:sender","entityPath":"$cbs"}
[2024-11-24 09:24:15.015] [INFO ] [1] [reactor-executor-367] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"Local link state is not closed.","connectionId":"MF_473fc2_1732438874867","linkName":"cbs:sender","entityPath":"$cbs","state":"ACTIVE"}
[2024-11-24 09:24:15.015] [WARN ] [1] [reactor-executor-367] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"Error in SendLinkHandler. Disposing unconfirmed sends.","exception":"The connection was closed by container '202d78bdc70b4e5a81578c17a4381207_G16' because it did not have any active links in the past 300000 milliseconds. TrackingId:202d78bdc70b4e5a81578c17a4381207_G16, SystemTracker:gateway10, Timestamp:2024-11-24T09:24:15, errorContext[NAMESPACE: name_dummyservicebus.windows.net. ERROR CONTEXT: N/A, PATH: $cbs, REFERENCE_ID: cbs:sender, LINK_CREDIT: 98]","connectionId":"MF_473fc2_1732438874867","linkName":"cbs"}
[2024-11-24 09:24:15.015] [INFO ] [1] [reactor-executor-367] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"onLinkRemoteClose","connectionId":"MF_473fc2_1732438874867","errorCondition":"amqp:connection:forced","errorDescription":"The connection was closed by container '202d78bdc70b4e5a81578c17a4381207_G16' because it did not have any active links in the past 300000 milliseconds. TrackingId:202d78bdc70b4e5a81578c17a4381207_G16, SystemTracker:gateway10, Timestamp:2024-11-24T09:24:15","linkName":"cbs:receiver","entityPath":"$cbs"}
[2024-11-24 09:24:15.015] [INFO ] [1] [reactor-executor-367] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"Local link state is not closed.","connectionId":"MF_473fc2_1732438874867","linkName":"cbs:receiver","entityPath":"$cbs","state":"ACTIVE"}
[2024-11-24 09:24:15.015] [INFO ] [1] [reactor-executor-367] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"onSessionRemoteClose","connectionId":"MF_473fc2_1732438874867","errorCondition":"amqp:connection:forced","errorDescription":"The connection was closed by container '202d78bdc70b4e5a81578c17a4381207_G16' because it did not have any active links in the past 300000 milliseconds. TrackingId:202d78bdc70b4e5a81578c17a4381207_G16, SystemTracker:gateway10, Timestamp:2024-11-24T09:24:15","sessionName":"cbs-session","sessionId":"H_963b91_1732438874920"}
[2024-11-24 09:24:15.015] [INFO ] [1] [reactor-executor-367] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"onSessionRemoteClose closing a local session.","connectionId":"MF_473fc2_1732438874867","errorCondition":"amqp:connection:forced","errorDescription":"The connection was closed by container '202d78bdc70b4e5a81578c17a4381207_G16' because it did not have any active links in the past 300000 milliseconds. TrackingId:202d78bdc70b4e5a81578c17a4381207_G16, SystemTracker:gateway10, Timestamp:2024-11-24T09:24:15","sessionName":"cbs-session"}
[2024-11-24 09:24:15.015] [WARN ] [1] [reactor-executor-367] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"Session endpoint state signaled error.","exception":"onSessionRemoteClose connectionId[MF_473fc2_1732438874867], entityName[cbs-session] condition[Error{condition=amqp:connection:forced, description='The connection was closed by container '202d78bdc70b4e5a81578c17a4381207_G16' because it did not have any active links in the past 300000 milliseconds. TrackingId:202d78bdc70b4e5a81578c17a4381207_G16, SystemTracker:gateway10, Timestamp:2024-11-24T09:24:15', info=null}], errorContext[NAMESPACE: name_dummyservicebus.windows.net. ERROR CONTEXT: N/A, PATH: cbs-session]","connectionId":"MF_473fc2_1732438874867","sessionName":"cbs-session","sessionId":"H_963b91_1732438874920"}
[2024-11-24 09:24:15.015] [INFO ] [1] [reactor-executor-367] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"Evicting session terminated with error.","exception":"onSessionRemoteClose connectionId[MF_473fc2_1732438874867], entityName[cbs-session] condition[Error{condition=amqp:connection:forced, description='The connection was closed by container '202d78bdc70b4e5a81578c17a4381207_G16' because it did not have any active links in the past 300000 milliseconds. TrackingId:202d78bdc70b4e5a81578c17a4381207_G16, SystemTracker:gateway10, Timestamp:2024-11-24T09:24:15', info=null}], errorContext[NAMESPACE: name_dummyservicebus.windows.net. ERROR CONTEXT: N/A, PATH: cbs-session]","connectionId":"MF_473fc2_1732438874867","sessionName":"cbs-session","sessionId":"H_963b91_1732438874920"}
[2024-11-24 09:24:15.015] [INFO ] [1] [reactor-executor-367] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"onConnectionRemoteClose","connectionId":"MF_473fc2_1732438874867","errorCondition":"amqp:connection:forced","errorDescription":"The connection was closed by container '202d78bdc70b4e5a81578c17a4381207_G16' because it did not have any active links in the past 300000 milliseconds. TrackingId:202d78bdc70b4e5a81578c17a4381207_G16, SystemTracker:gateway10, Timestamp:2024-11-24T09:24:15","hostName":"name_dummyservicebus.windows.net"}
[2024-11-24 09:24:15.015] [INFO ] [1] [reactor-executor-367] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"onTransportClosed","connectionId":"MF_473fc2_1732438874867","hostName":"name_dummyservicebus.windows.net"}
[2024-11-24 09:24:15.015] [INFO ] [1] [reactor-executor-367] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"onTransportClosed","connectionId":"MF_473fc2_1732438874867","hostName":"name_dummyservicebus.windows.net"}
[2024-11-24 09:24:15.015] [INFO ] [1] [reactor-executor-367] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"onConnectionLocalClose","connectionId":"MF_473fc2_1732438874867","hostName":"name_dummyservicebus.windows.net"}
[2024-11-24 09:24:15.015] [INFO ] [1] [reactor-executor-367] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"onConnectionUnbound","connectionId":"MF_473fc2_1732438874867","hostName":"name_dummyservicebus.windows.net","state":"CLOSED","remoteState":"CLOSED"}
[2024-11-24 09:24:15.015] [INFO ] [1] [reactor-executor-367] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"Disposing of ReactorConnection.","connectionId":"MF_473fc2_1732438874867","isTransient":false,"isInitiatedByClient":false,"shutdownMessage":"Connection handler closed."}
[2024-11-24 09:24:15.015] [INFO ] [1] [reactor-executor-367] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"closing the channel-cache.","connectionId":"MF_473fc2_1732438874867","linkName":"cbs"}
[2024-11-24 09:24:15.015] [INFO ] [1] [reactor-executor-367] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"onLinkFinal","connectionId":"MF_473fc2_1732438874867","linkName":"session_name_dummysession_name_dummy","entityPath":"session_name_dummy"}
[2024-11-24 09:24:15.015] [INFO ] [1] [reactor-executor-367] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"onSessionFinal.","connectionId":"MF_473fc2_1732438874867","errorCondition":"amqp:connection:forced","errorDescription":"The connection was closed by container '202d78bdc70b4e5a81578c17a4381207_G16' because it did not have any active links in the past 300000 milliseconds. TrackingId:202d78bdc70b4e5a81578c17a4381207_G16, SystemTracker:gateway10, Timestamp:2024-11-24T09:24:15","sessionName":"session_name_dummy","sessionId":"H_14c8b1_1732438874918"}
[2024-11-24 09:24:15.015] [INFO ] [1] [reactor-executor-367] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"onLinkFinal","connectionId":"MF_473fc2_1732438874867","linkName":"cbs:sender","entityPath":"$cbs"}
[2024-11-24 09:24:15.015] [INFO ] [1] [reactor-executor-367] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"onLinkFinal","connectionId":"MF_473fc2_1732438874867","linkName":"cbs:receiver","entityPath":"$cbs"}
[2024-11-24 09:24:15.015] [INFO ] [1] [reactor-executor-367] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"onSessionFinal.","connectionId":"MF_473fc2_1732438874867","errorCondition":"amqp:connection:forced","errorDescription":"The connection was closed by container '202d78bdc70b4e5a81578c17a4381207_G16' because it did not have any active links in the past 300000 milliseconds. TrackingId:202d78bdc70b4e5a81578c17a4381207_G16, SystemTracker:gateway10, Timestamp:2024-11-24T09:24:15","sessionName":"cbs-session","sessionId":"H_963b91_1732438874920"}
[2024-11-24 09:24:15.015] [INFO ] [1] [reactor-executor-367] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"onConnectionFinal","connectionId":"MF_473fc2_1732438874867","hostName":"name_dummyservicebus.windows.net"}
[2024-11-24 09:24:15.015] [INFO ] [1] [reactor-executor-367] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"session disposal is completed","connectionId":"MF_473fc2_1732438874867","sessionName":"cbs-session","sessionId":"H_963b91_1732438874920"}
[2024-11-24 09:24:15.015] [INFO ] [1] [reactor-executor-367] [] [com.azure.core.util.logging.LoggingEventBuilder] - {"az.sdk.message":"Closing executor.","connectionId":"MF_473fc2_1732438874867"}
```

**Comment by anuchandy** [comment]
Hi @dineshlalwani, thanks.

we need the logs for the requested duration (20 mins) and scope (debug, since app start) as mentioned earlier. Also note that, the logs should be captured from the application running in the environment where the thread leak occurred.

**Comment by dineshlalwani** [comment]
Hi @anuchandy, we are currently experiencing thread in prod environment. I'll try to get logs for you, but it might take time.

**Comment by dineshlalwani** [comment]
@anuchandy I have sent logs to the support team of Microsoft, I think they will reach out to you.

**Comment by anuchandy** [comment]
Hello @dineshlalwani,

Thanks for sharing the logs. I received it and, from the logs we can confirm that the application is successfully using `azure-messaging-servicebus:7.17.6` (with the V2 stack and the new cache), so you won't experience the `NullPointerException` and the known (now resolved) leak that some users experienced. 

That said, the application use case shows an _aggressive_ connections creation pattern. According to the logs, approximately 65 connections are created within the first ~30 seconds (each connection will have a reactor-executor-* thread associated with it). I'm not sure if it's intentional, but this use case can consume a quite a bit of CPU cycles with that many connections. Because the logs only span 20 minutes, it is unclear if this pattern of creating additional connections continues over time.

We can also see that with one of the connections was closed by the broker due to timeout, the thread, reactor-executor-65, associated with it was cleanup by the native Service Bus library. It can take up to a minute for cleanup to complete.

Since this is an indirect use of the `azure-messaging-servicebus` library through `spring-cloud-azure-stream-binder-servicebus`, it's unclear if the issue is due to an intentional application's usage pattern or anything else leading binder to request multiple connections. If it's intentional then it is expected to have many threads serving connections, and old threads being disposed (due to connection timeout) will co-exist with new connection threads for some time. If you confirm there is a leak, could you please create a minimal reproduction, push it to your GitHub repository and share here? I do not have expertise in Spring Stream Binder, so looping Moary @moarychan to review your code once the minimal reproduction is available.

**Comment by sabajpai-github** [comment]
Hello @anuchandy,

I am encountering the same issue and seeing similar error logs. Although I'm not using the com.azure.spring:spring-cloud-azure-stream-binder-servicebus library, and instead directly utilizing azure-messaging-servicebus:7.17.6 in my project, the error logs are still appearing. Is there something else I need to include or configure?

**Comment by dineshlalwani** [comment]
Hi @anuchandy,

Since we're using around 100 ASB binder queues, I think these connection requests are intentional.
My only concern was after connection time-out, threads were not getting disposed instead they were multiplying, which was causing high CPU usage.

After the recent changes which I did by excluding the old version of ASB and including new version explicitly, CPU usage seems fine. we'll continue to observe this and wait for Spring Stream Binder team to release the updated library.

**Comment by anuchandy** [comment]
Hello @sabajpai-github, this issue (42987) was specifically about a NPE which was addressed in 7.17.5 with "com.azure.core.amqp.cache" opt-in or 7.17.6+ without any need for opt-in. The broker initiated close calls (e.g., onSessionRemoteClose, onConnectionClose) are normal during inactivity and the library will automatically reconnect. So, you can ignore those. If you encounter anything impacting the use case, feel free to open an issue with details, I'm happy to assist.

**Comment by anuchandy** [comment]
Closing this issue given the thread leak and NPE are addressed in 7.1.76+
