### ISSUE TITLE
Access token was expired

### ISSUE THREAD

**Issue by m-moris** [Azure/azure-sdk-for-java#557]
When I am running a long time process, access token was expired and following exception occurred.

```
com.microsoft.windowsazure.exception.ServiceException: AuthenticationFailed: The access token expiry UTC time '11/17/2015 8:03:45 AM' is earlier than current UTC time '11/17/2015 8:09:34 AM'.
	at com.microsoft.windowsazure.exception.ServiceException.createFromJson(ServiceException.java:290)
	at com.microsoft.azure.management.compute.VirtualMachineOperationsImpl.listAll(VirtualMachineOperationsImpl.java:7501)
	at Main.main(Main.java:41)
```

I know that the access token is expired one hour. So following program is always acquire new access token and specifies it.

But I check http client request log, It always uses the same access token that specified the first.
As a result, you will get an exception when after one hour from the start of the process.

Thanks.

```Java
public class Main {

    final static String MANAGEMENT_URI = "https://management.core.windows.net/";
    final static String ARM_URL = "https://management.azure.net/";
    final static String ARM_AAD_URL = "https://login.windows.net/";

    public static void main(String[] args) throws InterruptedException {

        String subscriptionId = "<<your subscription>>";
        String tenantId       = "<<your tenant>>";
        String clientId       = "<<your client id>>";
        String clientKey      = "<<your client key>>";

        // output http request header
        // see : https://hc.apache.org/httpcomponents-client-ga/logging.html
        System.setProperty("org.apache.commons.logging.Log", "org.apache.commons.logging.impl.SimpleLog");
        System.setProperty("org.apache.commons.logging.simplelog.showdatetime", "true");
        System.setProperty("org.apache.commons.logging.simplelog.log.org.apache.http.headers", "DEBUG");

        while (true) {

            try {
                AuthenticationResult credentials = AuthHelper.getAccessTokenFromServicePrincipalCredentials(
                        MANAGEMENT_URI, ARM_AAD_URL, tenantId, clientId, clientKey);
                Configuration config = ManagementConfiguration.configure(null, new URI(ARM_URL), subscriptionId,
                        credentials.getAccessToken());
                ComputeManagementClient client = ComputeManagementService.create(config);
                ArrayList<VirtualMachine> vms = client.getVirtualMachinesOperations().listAll(null)
                        .getVirtualMachines();

                for (VirtualMachine vm : vms) {
                    System.out.println(vm.getName());
                }

            } catch (Exception e) {
                e.printStackTrace();
            }

            Thread.sleep(60000);
        }
    }
}
```

**Comment by devigned** [comment]
@jianghaolu does the new client runtime refresh the token if the token has expired?

**Comment by jianghaolu** [comment]
Hi @m-moris The current Java SDK library does not handle authentication. Since you are getting a token yourself you will have to refresh it from ADAL when the token expires.
Yes, the new client runtime will be able to handle refreshing tokens when the they expire. You can now see the new library in development in autorest branch.

**Comment by m-moris** [comment]
Hi @jianghaolu

My sample program of the last post is always acquire a new access token in the while-loop, and specified the access token. However, the access token that you specify for the first time it would have been cached by the SDK. So SDK is always use same access token. Do you have any problem with the sample program?

I'm trying to autorest branch SDK. The new SDK is working as expected. But it seems like including a lot of breaking change. I'm concerned that we have to change a lot of my programs. When will the new SDK be released?

Thanks.

**Comment by skossi** [comment]
@m-moris My team and I have bumped into the same problem. We found a workaround which bypasses the oldest token being cached (until the new library is released):

```
Configuration conf = ManagementConfiguration.configure(
				null,
				new URI(baseUri),
				subscriptionId,
				getAccessToken(managementUri, aadUri, tenantId, clientId, clientKey)
				);
		ArrayList<AdalAuthFilter> filter = new ArrayList<AdalAuthFilter>();
		conf.setProperty("AuthFilters", filter);
```

**Comment by m-moris** [comment]
@skossi 
I tried your workaround and it is working as expected.
Thanks.

**Comment by jianghaolu** [comment]
@skossi Thanks for providing the workaround.
@m-moris We don't have a release date yet because that will vary based on the service providers' agenda. We are looking at January when we have some beta bits released. We will maintain the old library at least until the final version of the new library is released.

**Comment by moshjeier** [comment]
Even with the workaround posted above I'm still seeing cached tokens. Are there any other suggestions or workarounds?

**Comment by jianghaolu** [comment]
This issue has been fixed in https://github.com/Azure/azure-sdk-for-java/pull/574. Will be release in 0.9.1.

**Comment by suresank** [comment]
All:

The post says that issue was fixed and my Fortune 500 customer experiencing issues yesterday. Any suggestions?

New-AzureRmResourceGroupDeployment : ExpiredAuthenticationToken: The access 
15:47:29 - token expiry UTC time '6/22/2016 10:47:26 PM' is earlier than current UTC time 
15:47:29 - '6/22/2016 10:47:28 PM'.

**Comment by jianghaolu** [comment]
@suresank  This looks like a powershell command. You can file an issue in the repo https://github.com/Azure/azure-powershell.

But they can try `Clear-AzureProfile` and log in again first.

**Comment by Sf18** [comment]
I still see the same error when using Java SDK. I am using using 1.18.0 version for azure-mgmt related packages. Is there any way to regenerate the token before deployment so it doesn't expire?

"ExpiredAuthenticationToken: The access token expiry UTC time is earlier than current UTC time Virtual Machine running Linux"

**Comment by Sf18** [comment]
@jianghaolu, any suggestions/recommendations ill be very helpful

**Comment by jianghaolu** [comment]
@Sf18 This issue is very old which is probably not related to your situation. For instance, the credentials for 1.18 management libraries are auto-renewed, if you are using a credential that extends from `AzureTokenCredentials`.

If you can provide a call stack or a code snippet I can help you look into it.
