### ISSUE TITLE
PostShutdownAction mismatch

### ISSUE THREAD

**Issue by paksv** [Azure/azure-sdk-for-java#560]
I'm using azure-management-compute v0.8.0 from maven, which is the latest one at the moment (http://mvnrepository.com/artifact/com.microsoft.azure/azure-management-compute)

The problem is that enum PostShutdownAction contains two items: STOPPED and STOPPEDDEALLOCATED. They are used in com.microsoft.windowsazure.management.compute.models.VirtualMachineShutdownParameters#setPostShutdownAction, which requires a PostShutdownAction object.

This value is used as .toString() during serialization:             (postShutdownActionElement.appendChild(requestDoc.createTextNode(parameters.getPostShutdownAction().toString())) in the com.microsoft.windowsazure.management.compute.VirtualMachineOperationsImpl#beginShuttingDownRoles. The problem began to occur when I updated my lib to 0.8.0, so I started to get "InvalidXmlRequest: The request body's XML was invalid or not correctly specified." when I attempted to shutdown my VM, because it the request body it expects PostShutdownAction to be not capitalized (https://msdn.microsoft.com/library/azure/jj157195.aspx?f=255&MSPPError=-2147217396).

I see the problem is already fixed in the code. Can you please publish an updated jar to maven, so users won't experience that problem anymore

**Comment by jianghaolu** [comment]
Hi @paksv the issue should be fixed in 0.8.3 and 0.9.0 is the latest out in maven (which the fix is also included). Please re-open the issue if it persists in 'com.microsoft.azure:azure-mgmt-compute:0.9.0'.

Thanks!

**Comment by paksv** [comment]
Unfortunately, I still can't see com.microsoft.azure:azure-mgmt-compute:0.9.0 in maven nexus:
http://mvnrepository.com/artifact/com.microsoft.azure/azure-management-compute

**Comment by jianghaolu** [comment]
Hi Sergey,

As listed in the package page, the package is renamed to azure-svc-mgmt-compute and moved. If you go to that package you will see all the newer versions.

Thanks!

**Comment by paksv** [comment]
yeah,I noticed that just after writing the message above. Sorry for not being attentive :)
