### ISSUE TITLE
OpenCensus page 404s

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-java#6595]
OpenCensus link here: 
https://github.com/Azure/azure-sdk-for-java/#client-ga-november-2019-releases

Points here:
https://github.com/Azure/azure-sdk-for-java/blob/azure-core-tracing-opencensus_1.0.0-preview.4/sdk/core/azure-core-tracing-opencensus/README.md

And that README has many 404s

**Comment by samvaity** [comment]
@jongio Thanks for informing. 
I believe this has been corrected in the new release `azure-core-tracing-opencensus_1.0.0-beta.5`.
Please try accessing https://github.com/Azure/azure-sdk-for-java/blob/azure-core-tracing-opencensus_1.0.0-beta.5/sdk/core/azure-core-tracing-opencensus/README.md#azure-opencensus-tracing-client-library-for-java for the most updated version of the package.

Do let us know if you are still having issues.

**Comment by jongio** [comment]
Still broken on master - I updated first link in the issue.  That points to the branch referenced above, but the master readme still points to preview.4

**Comment by samvaity** [comment]
@jongio That is correct. Root-level readme's are pending updates for the latest releases. They will soon be updated when all the packages are released. Have created this [issue](https://github.com/Azure/azure-sdk-for-java/issues/6619) to track it.

Meanwhile,  you can use this https://github.com/Azure/azure-sdk-for-java/blob/azure-core-tracing-opencensus_1.0.0-beta.5/sdk/core/azure-core-tracing-opencensus/README.md#azure-opencensus-tracing-client-library-for-java for OpenCensus tracing.

Thanks!

**Comment by samvaity** [comment]
@jongio The root level readme has been updated and you can now access it  https://github.com/Azure/azure-sdk-for-java/#client-ga-december-2019-releases. OpenCensus page https://github.com/Azure/azure-sdk-for-java/blob/azure-core-tracing-opencensus_1.0.0-beta.5/sdk/core/azure-core-tracing-opencensus/README.md
