### ISSUE TITLE
[BUG] downloadToFile should allow any size of data to be downloaded 

### ISSUE THREAD

**Issue by gapra-msft** [Azure/azure-sdk-for-java#7351]
Currently it is restricted by MAX_STAGE_BLOCK_BYTES

**Comment by rickle-msft** [comment]
This will be fixed implicitly when we deprecate blob.ParallelTransferOptions in favor of common.ParallelTransferOptions. For now, just move the bounds check in datalake's `populateAndApplyDefaults` into the upload method.

**Comment by ilikerei** [comment]
Please fix this issue or at least change the doc to not saying "Downloads the entire blob into a file specified by the path." It is very confusing and easily get file corrupted

**Comment by rickle-msft** [comment]
@ilikerei I think it's actually the title of this bug that is misleading. What is being unnecessarily limited here is the chunk size. There aren't restrictions on the size of a download in a single request like there are for uploads, so you should be able to pass an arbitrarily large chunk size for your download up to the full size of the blob. That said, given any chunk size, we will always issue the correct number of requests to download the entire file using that chunk size, so there shouldn't be any issue with corruption or downloading too little data here. 

Are you seeing issues of corruption or loss?

**Comment by ilikerei** [comment]
@rickle-msft Yes, even though the doc says  "Downloads the entire blob into a file specified by the path", the downloadToFile(String filePath) only download the first chunk (4MB by default). After days we found a lot of corrupted files, then I found the return code is 206. But downloadToFileWithResponse doesn't work as expected either because there is a max size check (100MB) on the blockSize.

**Comment by rickle-msft** [comment]
@ilikerei I just tested both forms of `downloadToFile` and got the entire 4GB file both times. Can you please share some more information on the size of your files and which version of the sdk you are using? If you are able to provide code that can reproduce this problem, that would be the most helpful.

**Comment by ilikerei** [comment]
@rickle-msft I've tried 12.6.0 and this issue is gone. Was using 12.2.0. So this issue is fixed. Thanks

**Comment by rickle-msft** [comment]
Excellent news! I think we still have the issue of limiting the block size, but thankfully no problems downloading an incorrect amount of data. :)

**Comment by gapra-msft** [comment]
Check to see if we fixed this implicitly
